spring:
  profiles: swarm
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  boot:
    admin:
      notify:
        mail:
          enabled: true
          from: ${spring.mail.username}
          to: '{cipher}AQAOyoDZMPpOUiofgFPgprgCM9A4t4zHo+HK2HUVCVIBwX5j+DK9HMVQ/1DPdy1hAuhFTtP+uA2qEihsCSkR35zHuXQgHBRIjXeaqaDrP30/R7leiegCVVNxBCE/Kx6Gk1D/HpjmvwH9ZYB/BI748U5Jd/TIZLhVZQq5TZmrx4KmIvOW+kZCByY3lGlBj6mrInMFBhZ3QNyAK+K6/W2GvCbuEXSoH+ZROUMC9jjTu5oXwcXTfOBEmi5kbgLGzCGeMheJgAN/9WvvU37iBg/o4krBCpANu95tvKGGxYGXprmXuAh6zqq91naWts3BqXRwnwySWfmhGL5ah0rJqYo9ZV2Gg+VIumiIUnamohQZX1KrAA80xbeoJNVZ/1H8aRaIBQlp4IuVXWqEPILa7OLgL8Pi'
  mail:
    host: '{cipher}AQCkzaB7YDvrTxNYvLEK6+8MmBja7tSvgqrjy+yjsbwfFbRFD2xsWoZzP/HAgHvj4ZNEfZz7vhIW5LnF6NS+lXgQBcZ7nKK/TrcnBkkv6xb2dVXif5EGrzYKlZj4fmR8d3O8YT/GoTSYn06DNLBbiukviTlmcLfj+8oZc+kNyvcmwKXOp+xIOc6XeNbT5b6qBLvGoazeiv8e6PbQYhPMZNKG+iGI2M2O6zvOfX6mSe1fJFfBlEoum15MErsv2iFhCbqzl3MD9Hk51U0l6kT0zqXEc5jSuhPupnzyImdZy4hA+e5m9xB3ywYWwOG1yhHmU4IwgqiyB97mbHAomUSshbY5xtn5cVZxECD7/jpBqwViHwmtmmQ4VBbBJ3YgnM4ZcyJI2dxVz2uesSglB37Zr2hi'
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:unknown}
    instance-id: ${spring.application.name}_${eureka.instance.hostname}
    non-secure-port: ${server.port:80}
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka1:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka2:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka3:8761/eureka/

logging:
  file:
    name: /opt/log/${eureka.instance.instance-id}.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    ROOT: INFO
    com.netflix.eureka.registry: WARN
    com.netflix.discovery.shared.resolver: WARN
    org.springframework.cloud.configclient: WARN

management:
  endpoint:
    health:
      show-details: when_authorized
    logfile:
      external-file: ${logging.file.name}
  health:
    mail:
      enabled: false

server:
  forward-headers-strategy: native
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port
    accesslog:
      enabled: false
      directory: /opt/log
      prefix: ${eureka.instance.instance-id}_access_log

bremersee:
  redis:
    embedded: false

---

spring:
  profiles: dev
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.7
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs
  mail:
    username: '{cipher}AQAuxiB+ICkws7gag2S/lmPZiOxefwox7SfeiTEzZiFh3kv6BqGCVMYOWbKeS757jOacCM7OxhOLIsjoqBGWIJfgCWuhN5+sPjQtR+/FIp+vkDajG6UG/nOx62goX6SDkC0IPoW52aNTaXbG0NX8kFXALbiOa6Cu8bTLXkNk6RUOd7AAwkNrTGJGdoOdrniFrIqKx++xb3uuUw1iwqsm/Z1C/CUbfZdGlfqRDBa6TQsdvzl4ydhl8AAQVwxPgyLfljAE6Wose2ao7rIZ70f3g6Dd0UdMULQNxCreX2YhM5eJnBtI6r+2OpjIt93ypSjCSmFgNtUjDA6dltBo+5rPWdknqy7xdXE7IheZJNsY7y2bA2nLfyzTVys4PFygmCQi4okXCgGjbBQVPo02G7kRV6L+'
    password: '{cipher}AQCESN/nMs5rDfg24+jzY6RMCMxCPkO1fO/3qYlncs1MrMJNN3mfLvusptpR8TbCOFVA9cHvWkMI5S5S3nSFFosKzrWNrlDPYbD7R830El2KXoEtB99twgkFx+LL7PckUN72n3MV+RHPAxDj/JgNMigImd5nmLHrA0Yjb2ijhQdvBeeAiozQjRHlizQadwSfV36v2O5wORHWbWDQBIrX7yPuYXhf7NP/lllycrTAr0fK1mvAY+Up3Utyhv6OzAI6AR+JQtrfQIFc2MXr6qnWFUE+GrpafuXPpQ+xdzrXDVTfYAD0pUU+qMmUTM9JisGN0trTlp/5sq3V/yZgkxrAStt+XvoeFGC6Oky8rbtZbbjzVZMC72QrRAsmze6YdvgNbBKiAzy/vsuJRLbT++ZrXegK'
  redis:
    password: '{cipher}AQCTSztA3PgRXP1gZTSCqkY5wPkSU6RbBrNYty1d8vd7NaXpbBFXb4eaCgH6R1nkd7Atmgmk5O+ozezlDTciWF7pZaN/IQt/ZkosrgGgoo5OkJ7zuB+zrdk8xr5CGN2fDIuXM6mHDOLt5EM4GnYuIJ42FyEZWCYu5CewgWvDGE59Fdp9/8wLsapbaE96OPgGDkhzGI7u/f7K8aHu+Z1MhTHsLAuFSy4ikBXKYAYdvvEb0izxrp684ME+Hr9l9Fq1/GEcFV7aw2ahoU0H/p35aHoGMYZpbkAqgZTmf3XrkJ8f/eGNgo7BcGwMciVOts3ZS5ezHwRhzngfmN4Utk+pjxHNtIkuNmAQZB1YRCzXGRE8pZ9su/wdL/BuCmE4xeDvoyGQAJJiUOdtNgC0hk6C9vwH'
    cluster:
      nodes: "192.168.1.41:6379,192.168.1.42:6379,192.168.1.43:6379,192.168.1.44:6379,192.168.1.45:6379,192.168.1.46:6379"

bremersee:
  auth:
    role-definitions:
      admin:
        - "ROLE_ADMIN"
        - "ROLE_DEV_ADMIN"
    eureka:
      username: '{cipher}AQBWGFbNNMTwWBU5Pqf9M2C5I3sazPDF6qPpVTCGhKtsvEHPBleMD3mYUfDwCFzZEgDoHEjjW1eVILrib+S1JrNbOwdkkg8QY7S1DgOEeiy6qNHUspI8j5bMCvoYkx/m0umGh6NfOUNCxk34PDjF6hH9K5kppRhAANUeLF/vtji/NF9WRl0jrmf79aHUyxVvu87Vpd70KdlP3s2UhADa5b6ePwLWwcfczQX5ibxnobXEaeOoPNFaKOXoC9SG7BACsgT3KPW0DIfu/GXi/skbAg0QZnvRn1uBYIXfkf8ix//lZFZ57M2WQDcHgdHlNf+/oOoo7IoTT4kjKuIwzUd9EK+aJYRtSez8VFk/rk+vG4E+UShfveH9WbJHY4UzIlWuNu8='
      password: '{cipher}AQBSTXFR5pCi01YxMJ7APS/OHt+dopgHHaKjl7irWamHxXYbJixsccArznT+LNWKzJoAYcx98KLoLVyMLbTs0HkS9ru2PnkvsWmhgnwcfcQwysTyxLNba/2NOIT6riujcvggJNxFhkT0iRhuF4Hk74gK64DBqYxbi99voGMQC6OI4FDYBb8ci6UxZsIVTkUYLHPv2nW9ympf/wUlgp2GBJh0IsCYQztXF1pTTlKXGly+Q6VlhwNlFZvQSE6jri17ANUoAG78247DIoDc1U/8OsHViVCcTVJA/Nl+D7fey7s99qAQBtzFW0Lz7rHf5wNn2nIUeCul9+ai9afWlF7m8iBGW/JhtNXf/9cRDc91jKhGfwqin48OYYnb+8oRkD/plWzw84e32c8SK6qr7D/aGri9'
    password-flow:
      client-id: '{cipher}AQCn5psgAScqhgrrvoTy3dznyStdezBT7znvqzhjN4GBth4ko8oNgUkHnq1Mu9mmKeAT3uN7PKgq4mrZ6n+qr5ByIKb3xY9HJk8KncI11haHm02uMSOFKF/EdmfVsUEX73KCbSYoCEWnDgDU0aJ4Yei+8jUypG6ngjI60Dte5Y1dPBdWPvJp2YJL5jCnG/b7+NQ2CFQAjU1jzMQQqoWVjyKEio5NjX5ZXDJb/Y6QfglIAFicyT2NcWL/Wg2BdBqh+hbQOXKoNKRkIOsi0vVQA1HTSVmw5/bb5ts0zRBRllbQvaxlRv7GVYr7BM8FA+cswDoBt6rkfvMXW6ShBIoZX+5+6jklpY5m6KQNPT3fMVA2KKkWp77kcYAyqEE8rybvr/0='
      client-secret: '{cipher}AQCI7vr0zuY0652/yRnX3UTHGReOrcR9Pb+1FWoLDbPS9lUB7N1AwnBFCt+NxZIZI/Oswv3FnIDRg3sOHHt9BLyaInaN3/ev/I9f6Qr79nLYZiPaJYeRNsWbUjIqpZUEIyU+rX5+91B9Jknj7hGL1OpPiVL3N+e3MHQQcKWJUPTvduHtSxVKmQ/cD423YO9NEYZSxJ+SLLhHXFg7mrEGH/FIdJGGpKOg3MA3RDOog250HzIag+8qvNMjRMuHGGlQujXcyYOXY8DHK4WcBj45Cv3B77acgY9Fts68/xTD6H9aG8Zw3cayKCvFx3MDAL5WWiXyEJTjlLDfJsyKLw6HoN2hoNjDksgqrlyacwDz0CT5xup//9LBRs+48AHaY9cy5uEMGpvQ3OwGhpdpxqtda7jMOjwfnDvB9EgL9a1VEuNgZg=='
      token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token

---

spring:
  profiles: prod
  cloud:
    inetutils:
      preferred-networks:
        - 172.16.1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/certs
  mail:
    username: '{cipher}AQAkL9eKoBKgEhQ8ZXntCun/pxFMNyOk6+FEy6NWOGAOoltJpnw/z4sk58cyI1xAz1jRcOVKPnOwdqIJv24K+02wdPx3wgc4vhRSbCa5nwplzE9bBqfCWnfc7a6TTMqo1c3o1xpwHrY+FpvLngfN3hGGxdYiWTosVOHRHKvjnkmNsHNBhQSRGpiPagdVrIx97lqnCSEGMHG6WoD2Hy73LN3avQ0S1ubSPO6cA9WV7eF8RISmyvxMB9RTXUnkvKOCddXhlLxFATWDYp3O8YZYM6K34bRb7Z5VU/0e1p3SgHwrgPDk1BwRNBxC44Mp0j//69VLz0y6q6ROvMkw0iXxgPasbY3nAXj6957N6jMdyd9l6fV/j8P3C33hFMGAtJOd3dgXoBnD2/lc+ghgnFSpiIrN'
    password: '{cipher}AQBKFd1S7+TikgQMFGZMxoJfFv+fVW1JLvyfIaK6iR5CVhFm3EwqNe7LxCis6++ZjmScX2l//W6oAkU1WIVi7UW+BMMJ3lZQ5yY8KlQiegci7GQeMqtwRPZsswy8f7HUUqQmsNaeVjlQc4tVR6ZsPHlaPB4J1Rbfrx0lNo0Fs53pVThSR6EqGZbz8zN1KKot7tXrzQXUjQGVozhTO6WzybD4QwhvOoF7qWADW6JZF9JHT7sgF61j+bzxf4pVRXY9Hl5bznpCJDjfVefPOo9tNzgwZRITSirOCMj2SsE2arYqZGpK8sSu41PAqKt1RSBUK5t13hmxGGU5yoRoOVPgOt40dRVE1BHWtePPEmpNaa9gSYD8WKrYpINtkJWdgHfJO32G/ubsa6KbEjh6RnIyVSfq'
  redis:
    password: '{cipher}AQAN3SBtcObu2mRWgqu3m+94OEroGqz6d7vZCIZcIKDI0WJAHmuQNXmtHW4zkemnBdpzR0OX2W749Abpk/8E8G5GuKK2E1tCIqDSG3ItAlhjJ6kFGjET0/oOaB2LFIXZNwqAz34Z2tc2OIu+7NtzGywQuLzrr7J8nH0PLjdvdGdAWyH06lxAuW/MsnJfiORW8CBmvsyjFEo2smlHY2jnMZPTEprVGYIJq670O+W1WokxVjjUEIow4zpczRTBiFn/J85UoQduju8aMTxQJEQAVsFpTNj6PBMEbSjVDxZfRqej80UgR9SXBU6z73GWzT6si9K6s2Az4parCKsp1UpB0ubvXFNI8ZddgfXEN7ccUM5JQpFuHA8KTfqylulL9LHxGbliQjrLi5lishbYfcrVQcBc'
    cluster:
      nodes: "192.168.1.51:6379,192.168.1.52:6379,192.168.1.53:6379,192.168.1.54:6379,192.168.1.55:6379,192.168.1.56:6379"

bremersee:
  auth:
    role-definitions:
      admin:
        - "ROLE_ADMIN"
        - "ROLE_PROD_ADMIN"
    eureka:
      username: '{cipher}AQAs/zyqDN6WusLJP5Lu4P8JK13EPMbvVJt01OSbbycBsGW9SQ/GChI51LMLLV6+TOjnGDLVqFBxHT06s37ugAIzPS9UlDtsNRsUx2hWyDsYW1AIH9dV1ikijuNgg3edTLJOJ2RhJkXmdb9+q3sdAMgBmOxQafbOftAvRKlhfBLkviYJG9Nv8Pi3P6RDP6eyCs8119wIv3LWe2BVJbLbo9Xn8FTAM8yC8a3D1SIG48J7stDWDln4WPDax8Tc/w4Qvrn3/y2fIIr+uSye4gXOaLs5YbqQTVtqGwpBj9eB/H6pSCOuxhj+plKP9cl13VIA31lEvJWzKAFOK8H//rI10cwcXoI7Ev7AEMKke58kifAvUyhPjLQl7Px6hhf3FB/TqM0='
      password: '{cipher}AQAgP5Z8+CWJX/sy5g9yF4qmCMSxfn6BfvXellyt+SXDLins5BSiRac7ppOD8bdE7g7QGD+GFyYjYYbWVEJdjtRmgGh3GIvOJNrIHzS8LF7SsyebpTP64Lc0hOgkH3RVOEtngItXTortn85FyVieYkQaP20ssHrYMSHvhaYYxSuBuFE2XTwXZMlg8Wvz3yW2hHDVMlRgz+kRZgc5P0COJbtjOXn0yR8MBB6CyzLjgG4Ul657rQZEPNgv+fduDxGvseK0yAM1XFBpfDLBlD5nCGO3w42b1UtR0LplK5SQH8WbD6NMYT4LA8SAUQDx4Q0ATNOnn14Au1GKzfZtflCKGbbakhG+BG/IrzvzNa/gjQxEkfx5+bvDx5jdIVqiD4c3T+V1v/OQgtIF+/7PeZK/3dL+'
    password-flow:
      client-id: '{cipher}AQCn5psgAScqhgrrvoTy3dznyStdezBT7znvqzhjN4GBth4ko8oNgUkHnq1Mu9mmKeAT3uN7PKgq4mrZ6n+qr5ByIKb3xY9HJk8KncI11haHm02uMSOFKF/EdmfVsUEX73KCbSYoCEWnDgDU0aJ4Yei+8jUypG6ngjI60Dte5Y1dPBdWPvJp2YJL5jCnG/b7+NQ2CFQAjU1jzMQQqoWVjyKEio5NjX5ZXDJb/Y6QfglIAFicyT2NcWL/Wg2BdBqh+hbQOXKoNKRkIOsi0vVQA1HTSVmw5/bb5ts0zRBRllbQvaxlRv7GVYr7BM8FA+cswDoBt6rkfvMXW6ShBIoZX+5+6jklpY5m6KQNPT3fMVA2KKkWp77kcYAyqEE8rybvr/0='
      client-secret: '{cipher}AQApRrcr8lUlFIdvHfzbpw8ibN1zkyUuIxrjUzqUyF4BvHOrVLg9EotTfFEo3CC8kOMwd6mjegnlFXj4dB9Rtc2edyjsXyCSRR/gf6vgBCJIx+xc5N6EqV7T7VAGoNtY1fct0T0efxKw+5BBTwYmPbGg/srOd3DOSYgMvwLTyX4vy9IxyhBF4xP7g4JaDoJO/K9YmITkwiIxCOA55t+pHepjrFOb4XH0F+s0u0AMlVfsjlVVdLUDXlM2gAc4fFh7OIyOdO+xgXggLgpnXN0eohIEqMTqMYoJ+0lxNssADF3RXqk/S0JX0labdbbb69kCYG6TRi6mLTp9QQeJ6WKYJqbAB5UP9GUjYdcYSV6DvOcLnFQUQ/QqKqijm3761FhAYL+rlpTuXVhdbGtEBXbiRbUR6GUfcGNdG+M6Da7qXkqCSQ=='
      token-endpoint: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/token
