some:
  # demo key
  key: '{cipher}AQCM5kGaVGrTTS6EyVL/FuxPAIpsOGpsOwgcmZQCCZgPwuMuL1hIq+sm9IKBjSdTvfX8OnfR7/P0HMpWtDJjXOB0iLGfSlVz+adk1qZUJIl1pc48q4l6drRAt9Z63TtrgJrFr1eBSmdGINVYpB8E77018eB4J2spZFGEmE4giP100UQEUVGrIYn9OV6ErgE/Gv52mB/5gWQ/81pyagSDk99cf3Hy1z++shUY5wpUbKV3eG3Hv0fxgs88P9N2nnzS3bKWviB4NE+w4kqVvCU92Rlk5NqGkbjbWv4EA0dlhy0oWWTq+rTlBsZhQGboKJLqC6VUuK5UY8nYlzQ6JOHLQ7DA0QEXpQzGOumpHsDmFI0B72iAf1xVTJKJgFKF0OVa4Lw='
  # real key
  #key: '{cipher}AQCykFAsEFUKMakvFcsmumDsTh4rxuf8bhutyGkItUDAVgOdPbVNTMTUJwya2pot5wmPX4UEXhCShQ+aDu42CMQz4ap78QP7fdcruQYAbimbhGDmL9voyhNDCYQ6ywUQTXj8VfVo+KOL/LtQymoWljhhFHmzsXEG/cojvh0jpYKthPidWOpcmS10uMvrMgPQn9sCGGB/L1EBQjQsMGV+QnQHPn7dRhbmIlm6BJnOyrQPyUv+mqBLQEGoWxSBkm9TQPSyMHW926qpkL5gVHXzV/TDMbY3T5Te4eqv23QKTyuKMJ6usROsG1BJ1WH+fXTSt4gJtA2xJUm7DSIJfiUM0GkDqJ5A9S5uiHj0g9CptP4sXSK0HNnOiakVXU7SGEc4byA='

---

spring:
  profiles: logfiles

logging:
  path: /var/log/my-app
  file:
    max-history: 25
