spring:
  profiles: demo
  mail:
    host: "false"
  sleuth:
    enabled: false
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://localhost:9411/
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    inetutils:
      preferred-networks:
        - 10.0.7
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://openid.dev.bremersee.org/auth/realms/demo/protocol/openid-connect/certs"

bremersee:
  cors:
    enable: false
  auth:
    eureka:
      username: '{cipher}AQBWGFbNNMTwWBU5Pqf9M2C5I3sazPDF6qPpVTCGhKtsvEHPBleMD3mYUfDwCFzZEgDoHEjjW1eVILrib+S1JrNbOwdkkg8QY7S1DgOEeiy6qNHUspI8j5bMCvoYkx/m0umGh6NfOUNCxk34PDjF6hH9K5kppRhAANUeLF/vtji/NF9WRl0jrmf79aHUyxVvu87Vpd70KdlP3s2UhADa5b6ePwLWwcfczQX5ibxnobXEaeOoPNFaKOXoC9SG7BACsgT3KPW0DIfu/GXi/skbAg0QZnvRn1uBYIXfkf8ix//lZFZ57M2WQDcHgdHlNf+/oOoo7IoTT4kjKuIwzUd9EK+aJYRtSez8VFk/rk+vG4E+UShfveH9WbJHY4UzIlWuNu8='
      password: '{cipher}AQBSTXFR5pCi01YxMJ7APS/OHt+dopgHHaKjl7irWamHxXYbJixsccArznT+LNWKzJoAYcx98KLoLVyMLbTs0HkS9ru2PnkvsWmhgnwcfcQwysTyxLNba/2NOIT6riujcvggJNxFhkT0iRhuF4Hk74gK64DBqYxbi99voGMQC6OI4FDYBb8ci6UxZsIVTkUYLHPv2nW9ympf/wUlgp2GBJh0IsCYQztXF1pTTlKXGly+Q6VlhwNlFZvQSE6jri17ANUoAG78247DIoDc1U/8OsHViVCcTVJA/Nl+D7fey7s99qAQBtzFW0Lz7rHf5wNn2nIUeCul9+ai9afWlF7m8iBGW/JhtNXf/9cRDc91jKhGfwqin48OYYnb+8oRkD/plWzw84e32c8SK6qr7D/aGri9'
  actuator:
    auth:
      enable-cors: false
      jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs
      password-flow:
        client-id: '{cipher}AQAy3UTXefUBsG02Bw4o3QuG4Xx1WhgYAycAHD+3650fzj1LBj+Zr7Q/Z0MIB7enuIYgEv7CvZa+QB1ZsVyFMyH27RKsAMZE1UNtNBm/tyjv3Qj1Bjc5jsGWV9tYYbL2TtZ8lE3ePyyhrC9S4Epkdx7ER3Ve/2/oMH7Yz/F+vLXmX4s0k1IkfpWia04Rul6+tKKnBHgJL37Ta53VF8BmisruaZ5jm6UzYlqbrTo9e6LbQkfex6hF80Texr2EJEKQVBAr09LkB1+uy5YHQCZ2EVve9/3wqVv/MbUGKPcRzNqF/L2yXcqBFH1MhWrd3BQoEKA7fPvGu40ZFJwqTBd+akOXADNVVl+fI3cM9Wdy4MiZc+ryWHj0tMucYyqekFk4JWo='
        client-secret: '{cipher}AQCv31YpVAl69lGzdhWREz/FNT6E9LFL/kbXPyL5H6OCgjLXM1kHmscMDDTr2H5ih59FrgyBxx/uWc41xYyx16jxZ+P6eSvTPK844hGcEYH0HF1+hBWLgOh+4DY0LOuHrUhuGbMJ9/wytCMvDYuFrmEroMM3IFxHNAC1vutYOF7hg7kCnYnePO4DmGeIYWR9h6HnKIJy1TDYy51vrAJBf5HLW1qnJi7mIgOjjNFj9AhIX1F6Rb2GoiNn0QGYtbYAOKmvUelyUq1r6hN60ABKNrotWbVxA57JlYBRUu+R/WIDU+gc/v/IIjyWsRGf+raxKgmkzjitWz8k17Df1JfWm+ioC4Dp7/Nnln7EgbXlUb27PDem/buZf5kj/qXqiEkLdc2Cydw2EM/4e/45338yyMLdHAZxAJT1ONKipdwE6stumQ=='
        token-endpoint: "https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token"
  domain-controller:
    company-name: "example.org"
    company-url: "https://example.org"
    group-base-dn: "ou=users,dc=example.org"
    user-base-dn: "ou=users,dc=example.org"
    dns-zone-base-dn: "ou=samdom,dc=example,dc=org"
    name-server-host: "ns.samdom.example.org"
    default-zone: "samdom.example.org"
    mail-with-credentials:
      sender: "no-reply@example.org"
      login-url: "https://web.dev.bremersee.org/dc-con/change-password"

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:unknown}
    instance-id: ${spring.application.name}_${eureka.instance.hostname}
    non-secure-port: ${server.port:80}
    metadata-map:
      user.name: '{cipher}AQBtTH9N2P5gRb1w27Snd4O0eben9jBkpWvLcaq8XO2MIO4O22tsNiQUIKBwYV6FulzQvy5hV5yRthjkgznJ0U6YzZB86WhijHxDG39fJ33OBTrnDid5MBMnDtE1TDbNz5QQwKrLgGsY+sNfXwyrAtpivPsk3yq0NxJDaqm5Dcix5M0oxAr4qyBQ4bVf6D/NuXb4hmWJtsa+yFI6gwsZimvVKVJaks4n6ruGEaJzgZuaCcAog2YtgF6B3v2xIaoKfyoRD2BwrfE+w4Hwy7Z0DjHxNFpQv6P1zJEUuqks/tuadhYSjxsUFB4ZHD8vfB1hyRQZbAcwvmJEwY2RoxuI4cUcD16byfFutq70WFISnl3ZeC9ebQBEFhuMiCO7fp9NryE='
      user.password: '{cipher}AQA+8KzLCa8EvZiGfF1089gugs09TduEFNy4d8QhCOtmKcly+sBM9HWPusazZjkDHE52m6tznRip4Wkcv9LbRvsevnZK0Cq3SkxB55ZTM+Mn0WzZMO9NEYv1H2DcX+sD+Ykr7RBuZTU1uYKvOMe+TpR24LBkg/Aa+1/xFdcrRwtNY5jRTCoUpzxI2ECT0zS/NL/21zuDBgj9QrPyHWUXVHd29icI4klF+pRfyCZrzx5J9lrd5lMQqU6eUfwPlfCGiKMdxftcINOXtkKywcBt+9LuEWQQTRKze1Vws9N2Hm2A0aQa/+0bgsmZcJ03i9saiHdyztj4PHnC9XxdkThfSlIslI/Qw7bLSRRHDAiv18rgxfytz8eiuytV8zOQW6IBByY='
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka1:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka2:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka3:8761/eureka/

logging:
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  file:
    name: /opt/log/${eureka.instance.instance-id}.log

management:
  endpoint:
    logfile:
      external-file: ${logging.file.name}

server:
  forward-headers-strategy: framework
  tomcat:
    use-relative-redirects: true
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port
    accesslog:
      enabled: false
      directory: /opt/log
      prefix: ${HOSTNAME}_access_log

---

spring:
  profiles: debian9
  mail:
    host: '{cipher}AQCkzaB7YDvrTxNYvLEK6+8MmBja7tSvgqrjy+yjsbwfFbRFD2xsWoZzP/HAgHvj4ZNEfZz7vhIW5LnF6NS+lXgQBcZ7nKK/TrcnBkkv6xb2dVXif5EGrzYKlZj4fmR8d3O8YT/GoTSYn06DNLBbiukviTlmcLfj+8oZc+kNyvcmwKXOp+xIOc6XeNbT5b6qBLvGoazeiv8e6PbQYhPMZNKG+iGI2M2O6zvOfX6mSe1fJFfBlEoum15MErsv2iFhCbqzl3MD9Hk51U0l6kT0zqXEc5jSuhPupnzyImdZy4hA+e5m9xB3ywYWwOG1yhHmU4IwgqiyB97mbHAomUSshbY5xtn5cVZxECD7/jpBqwViHwmtmmQ4VBbBJ3YgnM4ZcyJI2dxVz2uesSglB37Zr2hi'
    port: 465
    username: '{cipher}AQAMUNHL9CxvnXO401Rep+Ww9mkEew1JHmRhdlwtUCbEdVxqg+BHRc5LXhMCEMuON+Qg3lCmaGS173xtUmhNvbM+q8Gjv3Q9uqOpnOmuPnhD8yHiN5uhDqxslftxnZ+wdWjxNX5ydirgiJN+xiw6wY6kBjxyrXfYtwPt7dBW6V1fqor3juelWFtfnNoD4FCOdtiVSyp1wdp/dBXC/nGflsXKivkE1zmsW1VhlSfYO1GiefH0w5/usGFfCgqvyBezwkSQNyzsup/GsTqCGFEix6YwiKVernuzhLZ8lpLYnhCG/2VJllDwo4UrrIDNLGpeOcSU6o3P00uUGP5Rf0GcAEASQdt3R2ya1nA8fP9y56T6V1ZDpDOMf98WK/syMKmNGJF5z08BdxZ+SrRrsNA/1Fug'
    password: '{cipher}AQCP/t3GBpADnw6mnzNm1t5EJFev/nKgCWDEvFNNzj7nPU762hbW8B7YyRQKDuvETwPmQXy0CeJBGkcBdpswG+LpP1octk8AYNhNxkiyYHkdk0UV1vmEQG/Ho1Epfia2h/YIq24OlsdKC2MNzKYUGAoD9Rn+6BHxqfm9u5N5CCNJ/TX6xCvIoEhlMjnqvjOUOA7+sVILit7ZV0FoNoc5w0FfP7iSSePV5B3QAwbpQc1/EAk1ZBdCLCjNzytWLUYDSSwob7ZuX6xKAcvi7OTpqPEV/0BBGN9GcS11L4OyeaRkIte5fe9VJZEZ7Af4GA5tZPYAKFD1novgCXu4gD0mHkaJIuoCXvKvOAntKCRJ79d9TZFMgLSuMoNbNbduTgPiavU='
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
  cloud:
    inetutils:
      preferred-networks:
        - 192.168.1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/certs

bremersee:
  cors:
    enable: false
  auth:
    eureka:
      username: '{cipher}AQAs/zyqDN6WusLJP5Lu4P8JK13EPMbvVJt01OSbbycBsGW9SQ/GChI51LMLLV6+TOjnGDLVqFBxHT06s37ugAIzPS9UlDtsNRsUx2hWyDsYW1AIH9dV1ikijuNgg3edTLJOJ2RhJkXmdb9+q3sdAMgBmOxQafbOftAvRKlhfBLkviYJG9Nv8Pi3P6RDP6eyCs8119wIv3LWe2BVJbLbo9Xn8FTAM8yC8a3D1SIG48J7stDWDln4WPDax8Tc/w4Qvrn3/y2fIIr+uSye4gXOaLs5YbqQTVtqGwpBj9eB/H6pSCOuxhj+plKP9cl13VIA31lEvJWzKAFOK8H//rI10cwcXoI7Ev7AEMKke58kifAvUyhPjLQl7Px6hhf3FB/TqM0='
      password: '{cipher}AQAgP5Z8+CWJX/sy5g9yF4qmCMSxfn6BfvXellyt+SXDLins5BSiRac7ppOD8bdE7g7QGD+GFyYjYYbWVEJdjtRmgGh3GIvOJNrIHzS8LF7SsyebpTP64Lc0hOgkH3RVOEtngItXTortn85FyVieYkQaP20ssHrYMSHvhaYYxSuBuFE2XTwXZMlg8Wvz3yW2hHDVMlRgz+kRZgc5P0COJbtjOXn0yR8MBB6CyzLjgG4Ul657rQZEPNgv+fduDxGvseK0yAM1XFBpfDLBlD5nCGO3w42b1UtR0LplK5SQH8WbD6NMYT4LA8SAUQDx4Q0ATNOnn14Au1GKzfZtflCKGbbakhG+BG/IrzvzNa/gjQxEkfx5+bvDx5jdIVqiD4c3T+V1v/OQgtIF+/7PeZK/3dL+'
  actuator:
    auth:
      enable-cors: false
      jwk-set-uri: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/certs
      password-flow:
        client-id: '{cipher}AQAy3UTXefUBsG02Bw4o3QuG4Xx1WhgYAycAHD+3650fzj1LBj+Zr7Q/Z0MIB7enuIYgEv7CvZa+QB1ZsVyFMyH27RKsAMZE1UNtNBm/tyjv3Qj1Bjc5jsGWV9tYYbL2TtZ8lE3ePyyhrC9S4Epkdx7ER3Ve/2/oMH7Yz/F+vLXmX4s0k1IkfpWia04Rul6+tKKnBHgJL37Ta53VF8BmisruaZ5jm6UzYlqbrTo9e6LbQkfex6hF80Texr2EJEKQVBAr09LkB1+uy5YHQCZ2EVve9/3wqVv/MbUGKPcRzNqF/L2yXcqBFH1MhWrd3BQoEKA7fPvGu40ZFJwqTBd+akOXADNVVl+fI3cM9Wdy4MiZc+ryWHj0tMucYyqekFk4JWo='
        client-secret: '{cipher}AQB8i94cndh95i9T3/HcKuZlVXDMl9OXPf5cfjq0bd2HPR8zMSCIkXqpcQLisLoux+MB59RX7Ulp0/mQl1pSrVa4MLn9Ms4m2unhqGg/5n2onion9z+S2aaHtP1QdFU9rRo58aZ3NoZiVoxikuC7dENjl3J5RNGyO14GE/rD9RbEj62QgISFVISWpEJblY0VvlDHFPgEVFItVjZKmbjY1oIG1jmOBKYsc8uHY9W9iclAZCbnSqeUJXozAfWeEFv1syplPpqaLXvc0LMjuuw88/fZUGXVSu2Mm6tt9TO+xsRvYy4upzVOmUQIVxJ7A1IrKW49mxMNLfLQAkM++a1NDfqRC3eNT93JIY/x99la5GsvGGiW/q4mRsJSSZYIyoD+HwgtyXBQ3ZFzW5R4B1za+fwyNzoCamoyx3M2bLtxq9/z0Q=='
        token-endpoint: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/token

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:unknown}
    instance-id: ${spring.application.name}_${eureka.instance.hostname}
    non-secure-port: ${server.port:80}
    metadata-map:
      user.name: '{cipher}AQBtTH9N2P5gRb1w27Snd4O0eben9jBkpWvLcaq8XO2MIO4O22tsNiQUIKBwYV6FulzQvy5hV5yRthjkgznJ0U6YzZB86WhijHxDG39fJ33OBTrnDid5MBMnDtE1TDbNz5QQwKrLgGsY+sNfXwyrAtpivPsk3yq0NxJDaqm5Dcix5M0oxAr4qyBQ4bVf6D/NuXb4hmWJtsa+yFI6gwsZimvVKVJaks4n6ruGEaJzgZuaCcAog2YtgF6B3v2xIaoKfyoRD2BwrfE+w4Hwy7Z0DjHxNFpQv6P1zJEUuqks/tuadhYSjxsUFB4ZHD8vfB1hyRQZbAcwvmJEwY2RoxuI4cUcD16byfFutq70WFISnl3ZeC9ebQBEFhuMiCO7fp9NryE='
      user.password: '{cipher}AQA+8KzLCa8EvZiGfF1089gugs09TduEFNy4d8QhCOtmKcly+sBM9HWPusazZjkDHE52m6tznRip4Wkcv9LbRvsevnZK0Cq3SkxB55ZTM+Mn0WzZMO9NEYv1H2DcX+sD+Ykr7RBuZTU1uYKvOMe+TpR24LBkg/Aa+1/xFdcrRwtNY5jRTCoUpzxI2ECT0zS/NL/21zuDBgj9QrPyHWUXVHd29icI4klF+pRfyCZrzx5J9lrd5lMQqU6eUfwPlfCGiKMdxftcINOXtkKywcBt+9LuEWQQTRKze1Vws9N2Hm2A0aQa/+0bgsmZcJ03i9saiHdyztj4PHnC9XxdkThfSlIslI/Qw7bLSRRHDAiv18rgxfytz8eiuytV8zOQW6IBByY='
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka.bremersee.org/eureka/

logging:
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  file:
    name: /var/log/dc-con/dc-con.log
    max-history: 25

server:
  forward-headers-strategy: framework
  tomcat:
    use-relative-redirects: true
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port
    accesslog:
      enabled: true
      directory: /var/log/dc-con
      prefix: access_log

---

spring:
  profiles: ldap

bremersee:
  ldaptive:
    enabled: true
    use-unbound-id-provider: false
    ldap-url: ${LDAP_URL:ldaps://example.org:636}
    use-ssl: true
    use-start-tls: false
    bind-dn: '{cipher}AQBAyUg8HKpK2KNQxr89z/3tnpEuVuT4+2kbdgNq/ezxdi0254pRXn0GNOjTkIOT01tMrKPUcUBgZj/1WFkSuBD7H3Q0WR/tYMT644pZzwC4Jpn/j8SWRcHqJKDAq72W3tbVdOzG7v0mu+29hY6qcVx8/9+cZPYyScLz4CGUvSIx+xq1Hlv4hIbixvVCOPzJWoTpTuqGrYwXu0O3G1Wru+GhK0tfRlwnCbKyiac4yIa+HBAahMV548+oQqiD7AXXp6BDYIODo7kBBsQk3aFWIu9PdFZKeQrXgQ7zZ8SS0HPJ+mESt96nT+xDkur5PgwnmQUc6mEoNDGCoQBRpMEseAaS1HjiJCPs/ry9IyRtj1n9vLmkuTXHNc6351NtKZy4s4T6n+hA4zJdO1Gas4CPPJvPRjzNeLye78UiKXlR43X96g=='
    bind-credentials: '{cipher}AQBFsE6aRbmoiZfWYqR80BKl6mLOgB58tJ82RaKUScgqnNBXW+qBoXzkNwiQfWbahH3lGWRsV6QgZJOyXBWP0tB5ePRAhJCZcRi67zVyBXzqlvAXGn0RF97Qf260yBKoBVFrdEcGUODruuG0vb9SiGfLuxhSxhE0iGl4ubhWucDnS8bKiH3wW6qB0t7HYfHsHg/YkIgZDD0vgOpvAG+7ckIR9NXsH6LPCf4ai80KVC3ShPD8/gMGhv6DrSLAHoItxyO0u//Kb7iRPaVLvFh4RWd2KVhAbzeQAR3xYKLUkJGkpGd1WarKGDbkB2THaM6s2PL3toIwMMka6L7gYYj4GIIsJNZ3EDswKcDdpYcjZ53nGb1ZLF7ZKcYFKzOiHNPW+nZFpMZN7Iz/GR7OXj/Q/hP1'
    pooled: true
    min-pool-size: 5
    max-pool-size: 10
    validate-on-check-in: false
    validate-on-check-out: false
    validate-periodically: true
    validate-period: 300
    idle-time: 600
    block-wait-time: 10000
    search-validator:
      search-request:
        base-dn: '{cipher}AQBp1vdrl/J43sscxYkYtDoyvtm8UCgmxznDrSpiwrh24yJd5ltHW2cHamcOojU1Ro+h3gYLJqVY2dT17i19OHKxSBXQAUUTMmWazwOeFpqLAFBS21PWKt4j0rkDLTxq7FbNmpXhjWwap/5lPyjV8BHJkmJl27DRpb6yqqQ14LBf8XLaCm4GJn32wWCUkFI7TOXo5RbTO/0ggqbk+K2vHrSbI2bczfVjFrXOHbVOIPIB7eSi3o5oe+O9N/wkTO7mI7qvoByw1QFDyDgHbFxwePkmQKNQb+u3csGdgK7GiOnDJveIo9ASBR/1d9fcAP5cwdn0p4/211T1mznlC4J9vC2u7reCAq34/q7Sq1VvnTjhcNUSRJvxOwo9Uja6xEB9KRA2bYQk7nv2g4ikZU8x3DaO/GAxHrRbDGYL0KfilC1UwA=='
        search-filter:
          filter: (cn=Administrator)
        size-limit: 1
        search-scope: ONELEVEL
        return-attributes:
          - cn
  domain-controller:
    company-name: bremersee.org
    company-url: https://bremersee.org
    group-base-dn: '{cipher}AQBzcR5wqtrTPMinMCauElYfv0gIrssuefcqEyEDRvRLjlO7xBFwiPaoTQqSSLjaHi9hfFp/e2a/JDQIondWwXjDoXclP07lku8MW/HUyI8ekM/ZThuCLKbXo9X8uQu6qlRxn+LegifqyW4acypKlyN1ayRJYbZ9D71225FJ8W1myRaslAIripY7X1jmosHvHN8s+brK4vdWvqv1Im/OBSITq2kpELre3ncdYGs3lSZ0HR6s/Ygxr8pFd9uNpV2xlFTur5pNeF1CTc7g5vqpMRLrBdSxNR2WIN7ilI+pMiHcGNvsieYJ7Zrvu0mdMpmha/n1Lvz7lChaTyyL7QZMHg98Qbl/IEJdBj/IZsL0XBMkc3yn90dCS4BlKwkudBMzNY3RiqvOmr+niiyaO92TqAmoucxcooe0rniHyN2gTrEHbA=='
    user-base-dn: '{cipher}AQCwRh/8z7UomaFJ6cTregkGjtLrWgskasEol7M4ahCeDJuqa098m9B+iv3cI4TurFbHr8B04o0on1dwBhnRcDjET0qGWr1Njsu7gwyu2arLmFBUyfbaE8+NU5vGLgLYPKoA4ZpvYWdufGMcyXYz3dZOM1qy4W/zBUBWaibbhXMNi/Sa9l/4ysL9ObA90LXpbaSUtp5Z3QPACzV93CMdqHtzlfe7ha56HEPYYQTo5XUFvKbAncCgLfVGPYCc2xcEygYQaVbxRt2+N4fMjGU2O6uSELY86CXrs7OuevMvWc8OAc2GghQUY2kPdRHpJsViWSI/MafUhngAofYr8Ln3LV62IqJ3mCkVnsqDdO5U2ehvWW1iC/BdRbrxuevg/7+WH0niRXV+p8t9H0mCs7fB0o11rbG4R/8MQAOGPAlkjzmr5w=='
    dns-zone-base-dn: '{cipher}AQAsfkZ7j42SbYtfRBWfBRNEcxjkUKzQsxBzSl4GrNl5c4jrDOzM9rCTlEhM+WlP4k/Upy50CiyMBSWoBpdx0H0zCEFBDAt+cBtmj/8oKFmog8Hyg+7Z1F0IO+MoYVadjSp7QLnKeEApTegc98ZwUpCBq3qp5S8DUBitPZuZInmg+K70DIw60EQRFpfgwP9rehx5n95VvnxR4tucxm3XsxZ956oWm7xS/ZGdV7Loz8Ic31C00NXCfHTvvc2QVpz/BiZCsD4v/94BiD4kJqbiIiYoGb2krZbVmGSpePMILjsLRO4Sp4J3RcUWlliqw3y14wIFoTTlhfqlRaoeuSaScrRC/dFngJO03Pz1D/dEf/uR/j7h5WNRPm3gq8ET2MHeH5Ka5hoRhrx+GKoa34oeEDD5U7YU0dnTf4MY95LJaz52CdY1dTdbPD/CTtFIsicaTPU='
    name-server-host: ${NAME_SERVER:localhost}
    default-zone: '{cipher}AQABH6jsa9LIsR4CV+k3PAb4RcyJ561XSIPs1A1fWynR6AKVMcnQmC7CoOTaKzf6uKrdozRGGfleTu0CapvNscHjq69WStklzFIj1hEfa4IqgzYCnO0Tz8lMJUqnMdjpQLVeyWgy0666EbOo1ME3/N/fXhnRHcFt4Ich4UpC3+9s4x4K3ofwjpq6yROyoU6ePtaGQAkTKyMw30x8/t6tybucod7N9IbBpQbUs4Iqz+dvqykaWkO8OlDq+LMM2ANvepKvgGq4yP1WiR4vGl2Js45zw8TdgGjKyXBIBV3CTd1sXYKxsk3xxtoWWxDyPb//4Sv61kURz3ISJZkV7KOMrYVZ1Xy2WMj1m1guoYUCsBSfpik4AHYd1aMVGoSoRo3IoR3Z38cmB9lRjp5zZ1T7V/fA'
    mail-with-credentials:
      sender: ${spring.mail.username:no-reply@bremersee.org}
      login-url: https://web.bremersee.org/dc-con/change-password
