bremersee:
  access:
    ip-addresses:
      - "127.0.0.1/32"
      - "::1"
  security:
    oauth2:
      password-flow:
        client-id: omnia
        client-secret: '{cipher}AQAlg0j2ygkthXyK3O/6C/Nq29SJbKzwWxcz3cUb6Ihevsw9i3Fy+pu9EurbNxcGFoDvOFwpVfGhuVTHnZTYSrZn/dcP35j7gXC0/5IxCe9WTOyoDsifeL36BvdLuSgjKiZMytyho2b0+hDK1fkNNuUZ5pnnTRqDna8SUFCC5rCyquwmhM/rzzVmnl9h+b408ILC8ZeSdfo7Y0t4Cxv92cJCpQEwlRtTIdGS/CVns9l0ySFdQR25eNf+WtWiFyDEsOAt/4fv26jYjLuJ8XsvXtI/mXK3Ifejxh9e92JaLt2kctxNmzUz4rJw8rhAH/rRpxSoCOvKMzHaCXvtShJGQNpCSDQL/UPL30eGx3rc3UtMOwxFxV0uWaDd+7SYXYQW2C8Vrkb9HqBOv00Fl9UDPjVHnQ9MxlJ09o+xMDqEuG6eKA=='
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
  exception-mapping:
    api-paths:
      - /api/**
    default-exception-mapping-config:
      include-stack-trace: true
  domain-controller:
    company-name: bremersee.org
    company-url: https://bremersee.org
    group-base-dn: '{cipher}AQBzcR5wqtrTPMinMCauElYfv0gIrssuefcqEyEDRvRLjlO7xBFwiPaoTQqSSLjaHi9hfFp/e2a/JDQIondWwXjDoXclP07lku8MW/HUyI8ekM/ZThuCLKbXo9X8uQu6qlRxn+LegifqyW4acypKlyN1ayRJYbZ9D71225FJ8W1myRaslAIripY7X1jmosHvHN8s+brK4vdWvqv1Im/OBSITq2kpELre3ncdYGs3lSZ0HR6s/Ygxr8pFd9uNpV2xlFTur5pNeF1CTc7g5vqpMRLrBdSxNR2WIN7ilI+pMiHcGNvsieYJ7Zrvu0mdMpmha/n1Lvz7lChaTyyL7QZMHg98Qbl/IEJdBj/IZsL0XBMkc3yn90dCS4BlKwkudBMzNY3RiqvOmr+niiyaO92TqAmoucxcooe0rniHyN2gTrEHbA=='
    user-base-dn: '{cipher}AQCwRh/8z7UomaFJ6cTregkGjtLrWgskasEol7M4ahCeDJuqa098m9B+iv3cI4TurFbHr8B04o0on1dwBhnRcDjET0qGWr1Njsu7gwyu2arLmFBUyfbaE8+NU5vGLgLYPKoA4ZpvYWdufGMcyXYz3dZOM1qy4W/zBUBWaibbhXMNi/Sa9l/4ysL9ObA90LXpbaSUtp5Z3QPACzV93CMdqHtzlfe7ha56HEPYYQTo5XUFvKbAncCgLfVGPYCc2xcEygYQaVbxRt2+N4fMjGU2O6uSELY86CXrs7OuevMvWc8OAc2GghQUY2kPdRHpJsViWSI/MafUhngAofYr8Ln3LV62IqJ3mCkVnsqDdO5U2ehvWW1iC/BdRbrxuevg/7+WH0niRXV+p8t9H0mCs7fB0o11rbG4R/8MQAOGPAlkjzmr5w=='
    dns-zone-base-dn: '{cipher}AQAsfkZ7j42SbYtfRBWfBRNEcxjkUKzQsxBzSl4GrNl5c4jrDOzM9rCTlEhM+WlP4k/Upy50CiyMBSWoBpdx0H0zCEFBDAt+cBtmj/8oKFmog8Hyg+7Z1F0IO+MoYVadjSp7QLnKeEApTegc98ZwUpCBq3qp5S8DUBitPZuZInmg+K70DIw60EQRFpfgwP9rehx5n95VvnxR4tucxm3XsxZ956oWm7xS/ZGdV7Loz8Ic31C00NXCfHTvvc2QVpz/BiZCsD4v/94BiD4kJqbiIiYoGb2krZbVmGSpePMILjsLRO4Sp4J3RcUWlliqw3y14wIFoTTlhfqlRaoeuSaScrRC/dFngJO03Pz1D/dEf/uR/j7h5WNRPm3gq8ET2MHeH5Ka5hoRhrx+GKoa34oeEDD5U7YU0dnTf4MY95LJaz52CdY1dTdbPD/CTtFIsicaTPU='
    name-server-host: ${NAME_SERVER:localhost}
    default-zone: '{cipher}AQABH6jsa9LIsR4CV+k3PAb4RcyJ561XSIPs1A1fWynR6AKVMcnQmC7CoOTaKzf6uKrdozRGGfleTu0CapvNscHjq69WStklzFIj1hEfa4IqgzYCnO0Tz8lMJUqnMdjpQLVeyWgy0666EbOo1ME3/N/fXhnRHcFt4Ich4UpC3+9s4x4K3ofwjpq6yROyoU6ePtaGQAkTKyMw30x8/t6tybucod7N9IbBpQbUs4Iqz+dvqykaWkO8OlDq+LMM2ANvepKvgGq4yP1WiR4vGl2Js45zw8TdgGjKyXBIBV3CTd1sXYKxsk3xxtoWWxDyPb//4Sv61kURz3ISJZkV7KOMrYVZ1Xy2WMj1m1guoYUCsBSfpik4AHYd1aMVGoSoRo3IoR3Z38cmB9lRjp5zZ1T7V/fA'
    mail-with-credentials:
      sender: ${spring.mail.username:no-reply@bremersee.org}
      login-url: http://localhost:4200

eureka:
  client:
    enabled: false
#    register-with-eureka: true
#    prefer-same-zone-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://192.168.1.16:8761/eureka/}
#  instance:
#    health-check-url-path: /actuator/health
#    home-page-url-path: /actuator/info

logging:
  level:
    ROOT: info
    org.bremersee: debug
    org.springframework: info
#    org.springframework.security.oauth2: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8090

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT
  mail:
    host: mail.bremersee.org
    port: 465
    username: no-reply@bremersee.org
    password: '{cipher}AQCP/t3GBpADnw6mnzNm1t5EJFev/nKgCWDEvFNNzj7nPU762hbW8B7YyRQKDuvETwPmQXy0CeJBGkcBdpswG+LpP1octk8AYNhNxkiyYHkdk0UV1vmEQG/Ho1Epfia2h/YIq24OlsdKC2MNzKYUGAoD9Rn+6BHxqfm9u5N5CCNJ/TX6xCvIoEhlMjnqvjOUOA7+sVILit7ZV0FoNoc5w0FfP7iSSePV5B3QAwbpQc1/EAk1ZBdCLCjNzytWLUYDSSwob7ZuX6xKAcvi7OTpqPEV/0BBGN9GcS11L4OyeaRkIte5fe9VJZEZ7Af4GA5tZPYAKFD1novgCXu4gD0mHkaJIuoCXvKvOAntKCRJ79d9TZFMgLSuMoNbNbduTgPiavU='
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
  sleuth:
    enabled: false
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://localhost:9411/
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs

---

spring:
  profiles: ldap

bremersee:
  ldaptive:
    ldap-url: ${LDAP_URL:ldaps://example.org:636}
    use-ssl: true
    use-start-tls: false
    bind-dn: '{cipher}AQBAyUg8HKpK2KNQxr89z/3tnpEuVuT4+2kbdgNq/ezxdi0254pRXn0GNOjTkIOT01tMrKPUcUBgZj/1WFkSuBD7H3Q0WR/tYMT644pZzwC4Jpn/j8SWRcHqJKDAq72W3tbVdOzG7v0mu+29hY6qcVx8/9+cZPYyScLz4CGUvSIx+xq1Hlv4hIbixvVCOPzJWoTpTuqGrYwXu0O3G1Wru+GhK0tfRlwnCbKyiac4yIa+HBAahMV548+oQqiD7AXXp6BDYIODo7kBBsQk3aFWIu9PdFZKeQrXgQ7zZ8SS0HPJ+mESt96nT+xDkur5PgwnmQUc6mEoNDGCoQBRpMEseAaS1HjiJCPs/ry9IyRtj1n9vLmkuTXHNc6351NtKZy4s4T6n+hA4zJdO1Gas4CPPJvPRjzNeLye78UiKXlR43X96g=='
    bind-credential: '{cipher}AQBFsE6aRbmoiZfWYqR80BKl6mLOgB58tJ82RaKUScgqnNBXW+qBoXzkNwiQfWbahH3lGWRsV6QgZJOyXBWP0tB5ePRAhJCZcRi67zVyBXzqlvAXGn0RF97Qf260yBKoBVFrdEcGUODruuG0vb9SiGfLuxhSxhE0iGl4ubhWucDnS8bKiH3wW6qB0t7HYfHsHg/YkIgZDD0vgOpvAG+7ckIR9NXsH6LPCf4ai80KVC3ShPD8/gMGhv6DrSLAHoItxyO0u//Kb7iRPaVLvFh4RWd2KVhAbzeQAR3xYKLUkJGkpGd1WarKGDbkB2THaM6s2PL3toIwMMka6L7gYYj4GIIsJNZ3EDswKcDdpYcjZ53nGb1ZLF7ZKcYFKzOiHNPW+nZFpMZN7Iz/GR7OXj/Q/hP1'
    pooled: true
    min-pool-size: 5
    max-pool-size: 10
    validate-on-check-in: false
    validate-on-check-out: false
    validate-periodically: true
    validate-period: 300
    idle-time: 600
    block-wait-time: 10000
    search-validator:
      search-request:
        base-dn: '{cipher}AQBp1vdrl/J43sscxYkYtDoyvtm8UCgmxznDrSpiwrh24yJd5ltHW2cHamcOojU1Ro+h3gYLJqVY2dT17i19OHKxSBXQAUUTMmWazwOeFpqLAFBS21PWKt4j0rkDLTxq7FbNmpXhjWwap/5lPyjV8BHJkmJl27DRpb6yqqQ14LBf8XLaCm4GJn32wWCUkFI7TOXo5RbTO/0ggqbk+K2vHrSbI2bczfVjFrXOHbVOIPIB7eSi3o5oe+O9N/wkTO7mI7qvoByw1QFDyDgHbFxwePkmQKNQb+u3csGdgK7GiOnDJveIo9ASBR/1d9fcAP5cwdn0p4/211T1mznlC4J9vC2u7reCAq34/q7Sq1VvnTjhcNUSRJvxOwo9Uja6xEB9KRA2bYQk7nv2g4ikZU8x3DaO/GAxHrRbDGYL0KfilC1UwA=='
        search-filter:
          filter: (cn=Administrator)
        size-limit: 1
        search-scope: ONELEVEL
        return-attributes:
          - cn

---

spring:
  profiles: cli

---

spring:
  profiles: debian9

logging:
  path: /var/log/dc-con
  file:
    max-history: 25

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/dc-con
