bremersee:
  access:
    ip-addresses:
      - "127.0.0.1/32"
      - "::1"
  security:
    oauth2:
      password-flow:
        client-id: omnia
        client-secret: '{cipher}AQAlg0j2ygkthXyK3O/6C/Nq29SJbKzwWxcz3cUb6Ihevsw9i3Fy+pu9EurbNxcGFoDvOFwpVfGhuVTHnZTYSrZn/dcP35j7gXC0/5IxCe9WTOyoDsifeL36BvdLuSgjKiZMytyho2b0+hDK1fkNNuUZ5pnnTRqDna8SUFCC5rCyquwmhM/rzzVmnl9h+b408ILC8ZeSdfo7Y0t4Cxv92cJCpQEwlRtTIdGS/CVns9l0ySFdQR25eNf+WtWiFyDEsOAt/4fv26jYjLuJ8XsvXtI/mXK3Ifejxh9e92JaLt2kctxNmzUz4rJw8rhAH/rRpxSoCOvKMzHaCXvtShJGQNpCSDQL/UPL30eGx3rc3UtMOwxFxV0uWaDd+7SYXYQW2C8Vrkb9HqBOv00Fl9UDPjVHnQ9MxlJ09o+xMDqEuG6eKA=='
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
  exception-mapping:
    api-paths:
      - /api/**
    default-exception-mapping-config:
      include-stack-trace: true
  ldaptive:
    ldap-url: ${LDAP_URL:ldaps://example.org:636}
    use-ssl: true
    use-start-tls: false
    bind-dn: '{cipher}AQBAyUg8HKpK2KNQxr89z/3tnpEuVuT4+2kbdgNq/ezxdi0254pRXn0GNOjTkIOT01tMrKPUcUBgZj/1WFkSuBD7H3Q0WR/tYMT644pZzwC4Jpn/j8SWRcHqJKDAq72W3tbVdOzG7v0mu+29hY6qcVx8/9+cZPYyScLz4CGUvSIx+xq1Hlv4hIbixvVCOPzJWoTpTuqGrYwXu0O3G1Wru+GhK0tfRlwnCbKyiac4yIa+HBAahMV548+oQqiD7AXXp6BDYIODo7kBBsQk3aFWIu9PdFZKeQrXgQ7zZ8SS0HPJ+mESt96nT+xDkur5PgwnmQUc6mEoNDGCoQBRpMEseAaS1HjiJCPs/ry9IyRtj1n9vLmkuTXHNc6351NtKZy4s4T6n+hA4zJdO1Gas4CPPJvPRjzNeLye78UiKXlR43X96g=='
    bind-credential: '{cipher}AQBFsE6aRbmoiZfWYqR80BKl6mLOgB58tJ82RaKUScgqnNBXW+qBoXzkNwiQfWbahH3lGWRsV6QgZJOyXBWP0tB5ePRAhJCZcRi67zVyBXzqlvAXGn0RF97Qf260yBKoBVFrdEcGUODruuG0vb9SiGfLuxhSxhE0iGl4ubhWucDnS8bKiH3wW6qB0t7HYfHsHg/YkIgZDD0vgOpvAG+7ckIR9NXsH6LPCf4ai80KVC3ShPD8/gMGhv6DrSLAHoItxyO0u//Kb7iRPaVLvFh4RWd2KVhAbzeQAR3xYKLUkJGkpGd1WarKGDbkB2THaM6s2PL3toIwMMka6L7gYYj4GIIsJNZ3EDswKcDdpYcjZ53nGb1ZLF7ZKcYFKzOiHNPW+nZFpMZN7Iz/GR7OXj/Q/hP1'
    pooled: true
    min-pool-size: 3
    max-pool-size: 10
    validate-on-check-in: false
    validate-on-check-out: false
    validate-periodically: true
    validate-period: 300
    idle-time: 600
    block-wait-time: 10000
    search-validator:
      search-request:
        base-dn: '{cipher}AQA53HABfWRhUyGzZwk69utGvRG9gC5FbuTKfNw6nUqizsWSLghVsxdMHTrh2SwqaTYu1igPIkvsxo2Md6UPLmKARfvkc3uWD1YU2Xp+o4/+EpLas2d61tTfbCmgW5dMVqLd9fwmj036XL54AHNo34UkEJVuyalxtc1Ka6PdZIYzePCd6vpZYKHyeikbVTN0NB9pxJbqyxKl3ewM5pLBvjYGI5kMtpxs7x5R2cehl/mBSMvsy0zO6P5A762G43NBUy1xSfc7j8vLlaWyZ1xGI7LmYpS/btz/GfdBWitBqnDKdIBwQnuxYupBku77RLLwlLax81AFn1vxyjbmFlpq+1iDKc22DjOOcGRGJp6a0oneYPcQqOOI1kQG7EMFMsB8DO7FEpipriuOvI+c6BkUBxdg'
        search-filter:
          filter: (cn=Administrator)}
        size-limit: 1
        search-scope: ONELEVEL
        return-attributes:
          - cn
  domain-controller:
    group-base-dn: '{cipher}AQBzcR5wqtrTPMinMCauElYfv0gIrssuefcqEyEDRvRLjlO7xBFwiPaoTQqSSLjaHi9hfFp/e2a/JDQIondWwXjDoXclP07lku8MW/HUyI8ekM/ZThuCLKbXo9X8uQu6qlRxn+LegifqyW4acypKlyN1ayRJYbZ9D71225FJ8W1myRaslAIripY7X1jmosHvHN8s+brK4vdWvqv1Im/OBSITq2kpELre3ncdYGs3lSZ0HR6s/Ygxr8pFd9uNpV2xlFTur5pNeF1CTc7g5vqpMRLrBdSxNR2WIN7ilI+pMiHcGNvsieYJ7Zrvu0mdMpmha/n1Lvz7lChaTyyL7QZMHg98Qbl/IEJdBj/IZsL0XBMkc3yn90dCS4BlKwkudBMzNY3RiqvOmr+niiyaO92TqAmoucxcooe0rniHyN2gTrEHbA=='
    user-base-dn: '{cipher}AQCwRh/8z7UomaFJ6cTregkGjtLrWgskasEol7M4ahCeDJuqa098m9B+iv3cI4TurFbHr8B04o0on1dwBhnRcDjET0qGWr1Njsu7gwyu2arLmFBUyfbaE8+NU5vGLgLYPKoA4ZpvYWdufGMcyXYz3dZOM1qy4W/zBUBWaibbhXMNi/Sa9l/4ysL9ObA90LXpbaSUtp5Z3QPACzV93CMdqHtzlfe7ha56HEPYYQTo5XUFvKbAncCgLfVGPYCc2xcEygYQaVbxRt2+N4fMjGU2O6uSELY86CXrs7OuevMvWc8OAc2GghQUY2kPdRHpJsViWSI/MafUhngAofYr8Ln3LV62IqJ3mCkVnsqDdO5U2ehvWW1iC/BdRbrxuevg/7+WH0niRXV+p8t9H0mCs7fB0o11rbG4R/8MQAOGPAlkjzmr5w=='
    name-server-host: '{cipher}AQCWug0WcPyzL3uj+xKsGYSySqCzS7doO6RMEeUnQPO2hOSr7tRP0MP1seeOx+zl+un3ih9tGCCvcgaJVwF/ti+zrPPpGDXnbkedETnN/F3cW/PYb+dvFkqiCo62CjE3IRKsa9MQ51wZO8CwqQebbXLRLjPbcQWqkHOt6a4tpPLZgjRWHijcLGv/6+2rbhPlAGG1hBe7Lr76erDuYF9qqvk96640Uq5sFh5tPEFkqyrqfPF3mmyaUYXyX4xCupGQhbQ6TKHaVgw6KsN1e6BjhTt2YP2Ov6bQ1QvpP/9tzUdZGjfKhjpvf8hXODGvcupcD1K2HaTvyIIwJ7hVza/ecd406T11hr1CChaoaJQyzs0r44MWRRD8aL94O40IOaJzGdsyDLZ/TjZRmmXErMpmQWfg'

eureka:
  client:
    enabled: false
#    register-with-eureka: true
#    prefer-same-zone-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://192.168.1.16:8761/eureka/}
#  instance:
#    health-check-url-path: /actuator/health
#    home-page-url-path: /actuator/info

logging:
  level:
    ROOT: info
    org.bremersee: debug
    org.springframework: info
#    org.springframework.security.oauth2: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8090

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT
  sleuth:
    enabled: false
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://localhost:9411/
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs

---

spring:
  profiles: debian9

logging:
  path: /var/log/dc-con
  file:
    max-history: 25

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/dc-con

---

spring:
  profiles: ide
