spring:
  profiles: swarm
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
    peer-node-read-timeout-ms: 1000
    # see https://github.com/spring-cloud/spring-cloud-netflix/issues/1322
  instance:
    prefer-ip-address: true
    hostname: ${HOST_NAME}
    instance-id: ${HOST_NAME}
    metadata-map:
      user.name: '{cipher}AQBtTH9N2P5gRb1w27Snd4O0eben9jBkpWvLcaq8XO2MIO4O22tsNiQUIKBwYV6FulzQvy5hV5yRthjkgznJ0U6YzZB86WhijHxDG39fJ33OBTrnDid5MBMnDtE1TDbNz5QQwKrLgGsY+sNfXwyrAtpivPsk3yq0NxJDaqm5Dcix5M0oxAr4qyBQ4bVf6D/NuXb4hmWJtsa+yFI6gwsZimvVKVJaks4n6ruGEaJzgZuaCcAog2YtgF6B3v2xIaoKfyoRD2BwrfE+w4Hwy7Z0DjHxNFpQv6P1zJEUuqks/tuadhYSjxsUFB4ZHD8vfB1hyRQZbAcwvmJEwY2RoxuI4cUcD16byfFutq70WFISnl3ZeC9ebQBEFhuMiCO7fp9NryE='
      user.password: '{cipher}AQA+8KzLCa8EvZiGfF1089gugs09TduEFNy4d8QhCOtmKcly+sBM9HWPusazZjkDHE52m6tznRip4Wkcv9LbRvsevnZK0Cq3SkxB55ZTM+Mn0WzZMO9NEYv1H2DcX+sD+Ykr7RBuZTU1uYKvOMe+TpR24LBkg/Aa+1/xFdcrRwtNY5jRTCoUpzxI2ECT0zS/NL/21zuDBgj9QrPyHWUXVHd29icI4klF+pRfyCZrzx5J9lrd5lMQqU6eUfwPlfCGiKMdxftcINOXtkKywcBt+9LuEWQQTRKze1Vws9N2Hm2A0aQa/+0bgsmZcJ03i9saiHdyztj4PHnC9XxdkThfSlIslI/Qw7bLSRRHDAiv18rgxfytz8eiuytV8zOQW6IBByY='
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka1:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka2:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka3:8761/eureka/

logging:
  file:
    name: /opt/log/${HOST_NAME}.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  endpoint:
    logfile:
      external-file: ${logging.file.name}
  # Redis health check is broken: https://github.com/spring-projects/spring-boot/issues/22061 (will be fixed in 2.4.0)
  health:
    redis:
      enabled: false

server:
  forward-headers-strategy: native
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port
    accesslog:
      enabled: false
      directory: /opt/log
      prefix: ${HOST_NAME}_access_log

bremersee:
  redis:
    embedded: false

---

spring:
  profiles: local
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs

bremersee:
  auth:
    eureka:
      username: eureka
      password: eureka
    password-flow:
      client-id: '{cipher}AQBrXoktCBTT9dS4YjA3ZB8Jw7wTxwESGbyH+Y3a9c8+Ro3+D2QtO36eviqEuqibxD2/1e3huFw2BZJ7q0Rl/KUdMsxuVuhM21/1/hPI7fZY9K+haMgSrB2noc+3rzOQE7R37orqrL4ZuUBnMBnb4NVmPvC1LvvYVBSKlAckqLCRziJsZuzbW93DgDawnsCFy1zO51R+rXa8jyrpaRcjTTiRovok/BnuDaWTAoM+CudN9oX2N00x45f1CD8k5NMtCRXTbMi2/e+lWcU9aAdn+2O8NGAthEk8r10uY1FgbcH8WyaFwyKUNNP3rO3iFtyKHF/IAogi0L9WAVYTtDWDZJkRCZp4YLOn9WLdgxNDCyTPKKO2WmOOGogcN6yMNngCYNo='
      client-secret: '{cipher}AQCK18eLpNwMs14FI+al9qku8PlDc+hWWQwgjPXgET/nroA0F/QTQCiaoDodDckRZ6bWAoNZBoLsHsixFSdvyRN/7nGvG0YqRP0ZUPKB8B+pxTxmhNdnMvtn4fTf8/W2B0+swloXs1v+Sx+rnOlGTZYE/eOy0Wcl7DPp5ij0wvFw7ZGVVj1FFZHnN82Df3Tjv3Cr8dMSKG3mCrix9mto8ns5G2JnyCcZZOSqUn0F97DXmld8h64rI4ii6DS5ACuH+dlygV/u/K56DVlab2ArR2eG4Ha8CKOoEzVzbSFsYi6mcLa2Lgs5/ibOOMMvYbt1lsv0F8CmiT1lv/E6nK27A0ULxgwp2La+I8U2JD2u5uqTvSswO0RkVf2BuhDuuehiCKbo9DmyOmUH+NkKwV9mTE69rw9I2EJx84TQVCQkK911zA=='
      token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@localhost:${server.port}/eureka/

---

spring:
  profiles: dev
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.7
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs
  redis:
    password: '{cipher}AQCTSztA3PgRXP1gZTSCqkY5wPkSU6RbBrNYty1d8vd7NaXpbBFXb4eaCgH6R1nkd7Atmgmk5O+ozezlDTciWF7pZaN/IQt/ZkosrgGgoo5OkJ7zuB+zrdk8xr5CGN2fDIuXM6mHDOLt5EM4GnYuIJ42FyEZWCYu5CewgWvDGE59Fdp9/8wLsapbaE96OPgGDkhzGI7u/f7K8aHu+Z1MhTHsLAuFSy4ikBXKYAYdvvEb0izxrp684ME+Hr9l9Fq1/GEcFV7aw2ahoU0H/p35aHoGMYZpbkAqgZTmf3XrkJ8f/eGNgo7BcGwMciVOts3ZS5ezHwRhzngfmN4Utk+pjxHNtIkuNmAQZB1YRCzXGRE8pZ9su/wdL/BuCmE4xeDvoyGQAJJiUOdtNgC0hk6C9vwH'
    cluster:
      nodes: "192.168.1.41:6379,192.168.1.42:6379,192.168.1.43:6379,192.168.1.44:6379,192.168.1.45:6379,192.168.1.46:6379"

bremersee:
  auth:
    eureka:
      username: '{cipher}AQBWGFbNNMTwWBU5Pqf9M2C5I3sazPDF6qPpVTCGhKtsvEHPBleMD3mYUfDwCFzZEgDoHEjjW1eVILrib+S1JrNbOwdkkg8QY7S1DgOEeiy6qNHUspI8j5bMCvoYkx/m0umGh6NfOUNCxk34PDjF6hH9K5kppRhAANUeLF/vtji/NF9WRl0jrmf79aHUyxVvu87Vpd70KdlP3s2UhADa5b6ePwLWwcfczQX5ibxnobXEaeOoPNFaKOXoC9SG7BACsgT3KPW0DIfu/GXi/skbAg0QZnvRn1uBYIXfkf8ix//lZFZ57M2WQDcHgdHlNf+/oOoo7IoTT4kjKuIwzUd9EK+aJYRtSez8VFk/rk+vG4E+UShfveH9WbJHY4UzIlWuNu8='
      password: '{cipher}AQBSTXFR5pCi01YxMJ7APS/OHt+dopgHHaKjl7irWamHxXYbJixsccArznT+LNWKzJoAYcx98KLoLVyMLbTs0HkS9ru2PnkvsWmhgnwcfcQwysTyxLNba/2NOIT6riujcvggJNxFhkT0iRhuF4Hk74gK64DBqYxbi99voGMQC6OI4FDYBb8ci6UxZsIVTkUYLHPv2nW9ympf/wUlgp2GBJh0IsCYQztXF1pTTlKXGly+Q6VlhwNlFZvQSE6jri17ANUoAG78247DIoDc1U/8OsHViVCcTVJA/Nl+D7fey7s99qAQBtzFW0Lz7rHf5wNn2nIUeCul9+ai9afWlF7m8iBGW/JhtNXf/9cRDc91jKhGfwqin48OYYnb+8oRkD/plWzw84e32c8SK6qr7D/aGri9'
    password-flow:
      client-id: '{cipher}AQBrXoktCBTT9dS4YjA3ZB8Jw7wTxwESGbyH+Y3a9c8+Ro3+D2QtO36eviqEuqibxD2/1e3huFw2BZJ7q0Rl/KUdMsxuVuhM21/1/hPI7fZY9K+haMgSrB2noc+3rzOQE7R37orqrL4ZuUBnMBnb4NVmPvC1LvvYVBSKlAckqLCRziJsZuzbW93DgDawnsCFy1zO51R+rXa8jyrpaRcjTTiRovok/BnuDaWTAoM+CudN9oX2N00x45f1CD8k5NMtCRXTbMi2/e+lWcU9aAdn+2O8NGAthEk8r10uY1FgbcH8WyaFwyKUNNP3rO3iFtyKHF/IAogi0L9WAVYTtDWDZJkRCZp4YLOn9WLdgxNDCyTPKKO2WmOOGogcN6yMNngCYNo='
      client-secret: '{cipher}AQCK18eLpNwMs14FI+al9qku8PlDc+hWWQwgjPXgET/nroA0F/QTQCiaoDodDckRZ6bWAoNZBoLsHsixFSdvyRN/7nGvG0YqRP0ZUPKB8B+pxTxmhNdnMvtn4fTf8/W2B0+swloXs1v+Sx+rnOlGTZYE/eOy0Wcl7DPp5ij0wvFw7ZGVVj1FFZHnN82Df3Tjv3Cr8dMSKG3mCrix9mto8ns5G2JnyCcZZOSqUn0F97DXmld8h64rI4ii6DS5ACuH+dlygV/u/K56DVlab2ArR2eG4Ha8CKOoEzVzbSFsYi6mcLa2Lgs5/ibOOMMvYbt1lsv0F8CmiT1lv/E6nK27A0ULxgwp2La+I8U2JD2u5uqTvSswO0RkVf2BuhDuuehiCKbo9DmyOmUH+NkKwV9mTE69rw9I2EJx84TQVCQkK911zA=='
      token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token

---

spring:
  profiles: prod
  cloud:
    inetutils:
      preferred-networks:
        - 172.16.1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/certs
  redis:
    password: '{cipher}AQAN3SBtcObu2mRWgqu3m+94OEroGqz6d7vZCIZcIKDI0WJAHmuQNXmtHW4zkemnBdpzR0OX2W749Abpk/8E8G5GuKK2E1tCIqDSG3ItAlhjJ6kFGjET0/oOaB2LFIXZNwqAz34Z2tc2OIu+7NtzGywQuLzrr7J8nH0PLjdvdGdAWyH06lxAuW/MsnJfiORW8CBmvsyjFEo2smlHY2jnMZPTEprVGYIJq670O+W1WokxVjjUEIow4zpczRTBiFn/J85UoQduju8aMTxQJEQAVsFpTNj6PBMEbSjVDxZfRqej80UgR9SXBU6z73GWzT6si9K6s2Az4parCKsp1UpB0ubvXFNI8ZddgfXEN7ccUM5JQpFuHA8KTfqylulL9LHxGbliQjrLi5lishbYfcrVQcBc'
    cluster:
      nodes: "192.168.1.51:6379,192.168.1.52:6379,192.168.1.53:6379,192.168.1.54:6379,192.168.1.55:6379,192.168.1.56:6379"

bremersee:
  auth:
    eureka:
      username: '{cipher}AQAs/zyqDN6WusLJP5Lu4P8JK13EPMbvVJt01OSbbycBsGW9SQ/GChI51LMLLV6+TOjnGDLVqFBxHT06s37ugAIzPS9UlDtsNRsUx2hWyDsYW1AIH9dV1ikijuNgg3edTLJOJ2RhJkXmdb9+q3sdAMgBmOxQafbOftAvRKlhfBLkviYJG9Nv8Pi3P6RDP6eyCs8119wIv3LWe2BVJbLbo9Xn8FTAM8yC8a3D1SIG48J7stDWDln4WPDax8Tc/w4Qvrn3/y2fIIr+uSye4gXOaLs5YbqQTVtqGwpBj9eB/H6pSCOuxhj+plKP9cl13VIA31lEvJWzKAFOK8H//rI10cwcXoI7Ev7AEMKke58kifAvUyhPjLQl7Px6hhf3FB/TqM0='
      password: '{cipher}AQAgP5Z8+CWJX/sy5g9yF4qmCMSxfn6BfvXellyt+SXDLins5BSiRac7ppOD8bdE7g7QGD+GFyYjYYbWVEJdjtRmgGh3GIvOJNrIHzS8LF7SsyebpTP64Lc0hOgkH3RVOEtngItXTortn85FyVieYkQaP20ssHrYMSHvhaYYxSuBuFE2XTwXZMlg8Wvz3yW2hHDVMlRgz+kRZgc5P0COJbtjOXn0yR8MBB6CyzLjgG4Ul657rQZEPNgv+fduDxGvseK0yAM1XFBpfDLBlD5nCGO3w42b1UtR0LplK5SQH8WbD6NMYT4LA8SAUQDx4Q0ATNOnn14Au1GKzfZtflCKGbbakhG+BG/IrzvzNa/gjQxEkfx5+bvDx5jdIVqiD4c3T+V1v/OQgtIF+/7PeZK/3dL+'
    password-flow:
      client-id: '{cipher}AQAxY0ENqYRV6yyGyFycsXuGBboMOlGA7Fuq0GfBFdn0kcpCeQBsu5MfePfclrin2m1He6gQ+/HzejSGpauWHY30+G7t8jmLb6DwTFiL7AjqSFYcYtb9BOwerX3+mu9C8YMCCHwjC3b8BOdWxYNI65k6xFDjFWfIUpiVLLF5jlZY4klo10slrvDwWWabqszCipUQhYue9q0nXu7CzjkGMNkEenKY6Qj/pRniRN77TpfuiHF+5OptwK/LnPuEAfFRNJXbe8vGCgKeHGvYo2DBSMtnm7wxw8BkGW9bDsJSKu5+55SuAsq9ubH48rrlgsGqZ0JQ8o6Py6yatEjcbqop5j/oF8PeZplupe9IXEXE1MQrhmk6A2hyaslEIHFs0d2/oGI='
      client-secret: '{cipher}AQCD85ZU55kSC2tyU28U7AdQueKDOWM9PRZiJKKgkKegPqdpzBx3gvNJrmmnKZMMtv3mNO2gWws9RAIcpj//zgA8IwHIVDG3rJvUrscSpuBfryUf67/BteLaZgp4UcqbkX+Yp2b2dW6tWL84v4H5xEU+yBDNJ1PHVkPAmf83j4lChVxqfk8r0A/gRP6QMszO+YwcUEeX+DXE1m3Q2PV09AxXNZgTVzNj3TBZ6hSC/2JT3ODXUNrlOM+bbeXRkpx7FCekw05pA2waW9Xpl3BPVYoPjeI2pX7GsTUKSNTVGzrrn6v17DcdN5Fzq002HzNkWve5tu+QJKzupGcDeC1tZkY1uUAdw06OwLBvHJ4devJfow6qsq0/gzb+QI4eMse/AKUJr/2PAHCnKPIY4XWEguwDkZo8lFtOpTRavX9U34uNdA=='
      token-endpoint: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/token
