bremersee:
  access:
    application-access: "hasIpAddress('127.0.0.1/32') or hasIpAddress('::1')"
    actuator-access: "hasIpAddress('127.0.0.1/32') or hasIpAddress('::1')"
    client-user-name: "eureka"
    client-user-password: '{cipher}AQBSTXFR5pCi01YxMJ7APS/OHt+dopgHHaKjl7irWamHxXYbJixsccArznT+LNWKzJoAYcx98KLoLVyMLbTs0HkS9ru2PnkvsWmhgnwcfcQwysTyxLNba/2NOIT6riujcvggJNxFhkT0iRhuF4Hk74gK64DBqYxbi99voGMQC6OI4FDYBb8ci6UxZsIVTkUYLHPv2nW9ympf/wUlgp2GBJh0IsCYQztXF1pTTlKXGly+Q6VlhwNlFZvQSE6jri17ANUoAG78247DIoDc1U/8OsHViVCcTVJA/Nl+D7fey7s99qAQBtzFW0Lz7rHf5wNn2nIUeCul9+ai9afWlF7m8iBGW/JhtNXf/9cRDc91jKhGfwqin48OYYnb+8oRkD/plWzw84e32c8SK6qr7D/aGri9'
    actuator-user-name: "actuator"
    actuator-user-password: '{cipher}AQBOuviOYCyIG0Xv7O7x2OJZT7w7hYCAJYzxR6up2J1y2JPNG+p/O4ues8EMLh4bSpcaehYclKEiYckKOiIAb4j+0q4rRm83LMOTWB5PLtZn0oABt5BVeXg13mvSpeP1bCFsOuBCsv6hwLSTN8/4+2RMp1pam2XfCdh86RwYAS06ldmK8ooKg6Uc8x6G5UPGYRqCJJNK2D1Rxa0+yeLE6LLL74u9O2NDulLpUWHf17QuLL9rdsICUlpZ12tIn5KeOoS1EBuWit1OE1wYYz50CkALGG9F4kWouWyB8+LJQvDC2F1A2gMNKiq+FBNqGrQz2SlRPzeaMwU6ibGwwpUf2K4aaw3ebepS4reZfYTBrP/Knxq3Aw+c3sc5MGb9kumumjM='
    admin-user-name: "admin"
    admin-user-password: '{cipher}AQBrRsPHgo6S/bpBP43qspnwiyqH7PX3R55qZ9P6kHqn5dGIu+e9QBPoVZQDnmwuhm699jj+GlCJZC+PnKZeYifIoibCOO+Ar+YBs718v7Dmt7H/2YsiVag5xp9NsyNBuDNsw7fMYOLKYbPV3/bz6I6RaKzm89j3KM0Fx4FGvqDUhnawRj/9EmlXLpCX4dZdYyVFhfZ1VeFwx+m5I11fnENvTj0aqlbetpk/4NEgVxRrC6IFl8k7VVkEdyACB9Uq9odyQNE6JFahfcZR4mddRz1VJT1dXBMv1/SWOE4eoW+yDTrb3Uk5xA9hCqIYQnb6NETWjJ/UEMBSjZS3y81Sk5Re+7dCMQuuZ/srSIBZm931ECfDDWLduhFnoiEnkSuuxIs='

eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://${bremersee.access.client-user-name}:${bremersee.access.client-user-password}@eureka1:8761/eureka/,http://${bremersee.access.client-user-name}:${bremersee.access.client-user-password}@eureka2:8762/eureka/,http://${bremersee.access.client-user-name}:${bremersee.access.client-user-password}@eureka3:8763/eureka/"

---

spring:
  profiles: eureka1

info:
  app:
    name: eureka1

eureka:
  instance:
    hostname: eureka1
    instance-id: eureka1

server:
  port: 8761

---

spring:
  profiles: eureka2

info:
  app:
    name: eureka2

eureka:
  instance:
    hostname: eureka2
    instance-id: eureka2

server:
  port: 8762

---

spring:
  profiles: eureka3

info:
  app:
    name: eureka3

eureka:
  instance:
    hostname: eureka3
    instance-id: eureka3

server:
  port: 8763

---

spring:
  profiles: dev
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.7

bremersee:
  access:
    application-access: "hasIpAddress('127.0.0.1/32') or hasIpAddress('::1') or hasIpAddress('10.0.7.0/24')"
    actuator-access: "hasIpAddress('127.0.0.1/32') or hasIpAddress('::1') or hasIpAddress('10.0.7.0/24')"

---

spring:
  profiles: prod
  cloud:
    inetutils:
      preferred-networks:
        - 172.16.1


bremersee:
  access:
    application-access: "hasIpAddress('127.0.0.1/32') or hasIpAddress('::1') or hasIpAddress('172.16.1.0/24')"
    actuator-access: "hasIpAddress('127.0.0.1/32') or hasIpAddress('::1') or hasIpAddress('172.16.1.0/24')"
