spring:
  profiles: swarm

bremersee:
  security:
    authentication:
      enable-jwt-support: true
      application:
        admin-roles:
          - "ROLE_ADMIN"
          - "ROLE_EUREKA_ADMIN"

eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
  instance:
    prefer-ip-address: true
    hostname: ${HOST_NAME}
    instance-id: ${HOST_NAME}
  client:
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: /opt/log/${HOST_NAME}.log

management:
  endpoint:
    health:
      show-details: when_authorized
    logfile:
      external-file: ${logging.file.name}

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /opt/log
      prefix: ${HOST_NAME}_access_log

---

spring:
  profiles: local
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs

bremersee:
  security:
    authentication:
      enable-jwt-support: true
      eureka:
        username: eureka
        password: eureka
      application:
        admin-roles:
          - "ROLE_ADMIN"
          - "ROLE_USER"
          - "ROLE_EUREKA_ADMIN"
      password-flow:
        client-id: '{cipher}AQBrXoktCBTT9dS4YjA3ZB8Jw7wTxwESGbyH+Y3a9c8+Ro3+D2QtO36eviqEuqibxD2/1e3huFw2BZJ7q0Rl/KUdMsxuVuhM21/1/hPI7fZY9K+haMgSrB2noc+3rzOQE7R37orqrL4ZuUBnMBnb4NVmPvC1LvvYVBSKlAckqLCRziJsZuzbW93DgDawnsCFy1zO51R+rXa8jyrpaRcjTTiRovok/BnuDaWTAoM+CudN9oX2N00x45f1CD8k5NMtCRXTbMi2/e+lWcU9aAdn+2O8NGAthEk8r10uY1FgbcH8WyaFwyKUNNP3rO3iFtyKHF/IAogi0L9WAVYTtDWDZJkRCZp4YLOn9WLdgxNDCyTPKKO2WmOOGogcN6yMNngCYNo='
        client-secret: '{cipher}AQCK18eLpNwMs14FI+al9qku8PlDc+hWWQwgjPXgET/nroA0F/QTQCiaoDodDckRZ6bWAoNZBoLsHsixFSdvyRN/7nGvG0YqRP0ZUPKB8B+pxTxmhNdnMvtn4fTf8/W2B0+swloXs1v+Sx+rnOlGTZYE/eOy0Wcl7DPp5ij0wvFw7ZGVVj1FFZHnN82Df3Tjv3Cr8dMSKG3mCrix9mto8ns5G2JnyCcZZOSqUn0F97DXmld8h64rI4ii6DS5ACuH+dlygV/u/K56DVlab2ArR2eG4Ha8CKOoEzVzbSFsYi6mcLa2Lgs5/ibOOMMvYbt1lsv0F8CmiT1lv/E6nK27A0ULxgwp2La+I8U2JD2u5uqTvSswO0RkVf2BuhDuuehiCKbo9DmyOmUH+NkKwV9mTE69rw9I2EJx84TQVCQkK911zA=='
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://${bremersee.security.authentication.eureka.username}:${bremersee.security.authentication.eureka.password}@localhost:${server.port}/eureka/

---

spring:
  profiles: dev
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.7
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs

bremersee:
  security:
    authentication:
      eureka:
        username: '{cipher}AQBWGFbNNMTwWBU5Pqf9M2C5I3sazPDF6qPpVTCGhKtsvEHPBleMD3mYUfDwCFzZEgDoHEjjW1eVILrib+S1JrNbOwdkkg8QY7S1DgOEeiy6qNHUspI8j5bMCvoYkx/m0umGh6NfOUNCxk34PDjF6hH9K5kppRhAANUeLF/vtji/NF9WRl0jrmf79aHUyxVvu87Vpd70KdlP3s2UhADa5b6ePwLWwcfczQX5ibxnobXEaeOoPNFaKOXoC9SG7BACsgT3KPW0DIfu/GXi/skbAg0QZnvRn1uBYIXfkf8ix//lZFZ57M2WQDcHgdHlNf+/oOoo7IoTT4kjKuIwzUd9EK+aJYRtSez8VFk/rk+vG4E+UShfveH9WbJHY4UzIlWuNu8='
        password: '{cipher}AQBSTXFR5pCi01YxMJ7APS/OHt+dopgHHaKjl7irWamHxXYbJixsccArznT+LNWKzJoAYcx98KLoLVyMLbTs0HkS9ru2PnkvsWmhgnwcfcQwysTyxLNba/2NOIT6riujcvggJNxFhkT0iRhuF4Hk74gK64DBqYxbi99voGMQC6OI4FDYBb8ci6UxZsIVTkUYLHPv2nW9ympf/wUlgp2GBJh0IsCYQztXF1pTTlKXGly+Q6VlhwNlFZvQSE6jri17ANUoAG78247DIoDc1U/8OsHViVCcTVJA/Nl+D7fey7s99qAQBtzFW0Lz7rHf5wNn2nIUeCul9+ai9afWlF7m8iBGW/JhtNXf/9cRDc91jKhGfwqin48OYYnb+8oRkD/plWzw84e32c8SK6qr7D/aGri9'
      password-flow:
        client-id: '{cipher}AQBrXoktCBTT9dS4YjA3ZB8Jw7wTxwESGbyH+Y3a9c8+Ro3+D2QtO36eviqEuqibxD2/1e3huFw2BZJ7q0Rl/KUdMsxuVuhM21/1/hPI7fZY9K+haMgSrB2noc+3rzOQE7R37orqrL4ZuUBnMBnb4NVmPvC1LvvYVBSKlAckqLCRziJsZuzbW93DgDawnsCFy1zO51R+rXa8jyrpaRcjTTiRovok/BnuDaWTAoM+CudN9oX2N00x45f1CD8k5NMtCRXTbMi2/e+lWcU9aAdn+2O8NGAthEk8r10uY1FgbcH8WyaFwyKUNNP3rO3iFtyKHF/IAogi0L9WAVYTtDWDZJkRCZp4YLOn9WLdgxNDCyTPKKO2WmOOGogcN6yMNngCYNo='
        client-secret: '{cipher}AQCK18eLpNwMs14FI+al9qku8PlDc+hWWQwgjPXgET/nroA0F/QTQCiaoDodDckRZ6bWAoNZBoLsHsixFSdvyRN/7nGvG0YqRP0ZUPKB8B+pxTxmhNdnMvtn4fTf8/W2B0+swloXs1v+Sx+rnOlGTZYE/eOy0Wcl7DPp5ij0wvFw7ZGVVj1FFZHnN82Df3Tjv3Cr8dMSKG3mCrix9mto8ns5G2JnyCcZZOSqUn0F97DXmld8h64rI4ii6DS5ACuH+dlygV/u/K56DVlab2ArR2eG4Ha8CKOoEzVzbSFsYi6mcLa2Lgs5/ibOOMMvYbt1lsv0F8CmiT1lv/E6nK27A0ULxgwp2La+I8U2JD2u5uqTvSswO0RkVf2BuhDuuehiCKbo9DmyOmUH+NkKwV9mTE69rw9I2EJx84TQVCQkK911zA=='
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://${bremersee.security.authentication.eureka.username}:${bremersee.security.authentication.eureka.password}@eureka1:8761/eureka/,http://${bremersee.security.authentication.eureka.username}:${bremersee.security.authentication.eureka.password}@eureka2:8761/eureka/,http://${bremersee.security.authentication.eureka.username}:${bremersee.security.authentication.eureka.password}@eureka3:8761/eureka/

---

spring:
  profiles: prod
  cloud:
    inetutils:
      preferred-networks:
        - 172.16.1
