bremersee:
  access:
    default-access: "hasIpAddress('127.0.0.1') or hasIpAddress('::1') or hasIpAddress('172.16.238.0/24') or hasIpAddress('fd2d:6169:6c63:6f77::/64') or hasAuthority('ROLE_EUREKA')"

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.bremersee: INFO

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port

spring:
  security:
    user:
      name: '{cipher}AQBZR2ZKdhEtiUQsPLLq1L6F+FpUpdBoK71svyRqz+XXcsV7QzTT2PF56UAle77ztR+9pKGsVjX+jf0PAhkrV2wA8NhpPdcGV0Ezsq99nwF/bPNnEhqWbiMUD6NLyeaUFu8lUpdL4vmEa3VUtc27mWY9N1ryT5v1a8jVCAmZWzz2AiLzDqwkw77eEYo4xB+p4+U8obuZoD9uEmISJ158/055o9DEix7xmMUR0scsl4LeENnIU/Ff+wjFukG552wGUFIeQrUAb82O3gAibbLwCFnUAbUNx2XAmvP3lKHOZjeSd23ApcwXaYoUfR+2+Y+IFpfDT9Olrh4MWnoojGy/nQfRQcGrz1HVUgkpjj9VT1RSzRVQ7bvj6KWXx2y3R+fFLmQ='
      password: '{cipher}AQA2mRu/pgoLZ4wyLwoXoj5yUuCMxpWN2gmyxRYQtmplBTDOrCRgcrr4fTuLAzkdQn+DBQo498NT+VMKG7LYze/A9I+rn/eGNLt+0S/MLYlWGxl2NR6RTncVlQhESp+OQqeAiefESbdudGXjQFOGlJdo/ZdZz0Kq7/DptXEpLReKs2FcTh5uKtit4zFsvOZq2Qb4Y+VxrJSi4uq1NfhKfTVfp4dvoQqb9UHStgcUUJb7hUaFd3K0cKlUZL3yvFAUnzjdZnWwKgLyJhDaLz+Ng/7QoHTUfw9k/QLZofumpfipfKxzlZl2dk1c768i6Wa7AEgzpxsAfmHM4oB+CEwyOkT8LMJQagKin5GzLqVHpK1HLmPe2BxDFIdO/cItu/1A25XufF3B/wYD+28njNQQ3wb1wZmxZKiiw5Q7X71syD3t/w=='
      roles: EUREKA

---

spring:
  profiles: base

---

spring:
  profiles: logfiles

logging:
  path: /var/log/eureka
  file:
    max-history: 25

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/eureka

---

spring:
  profiles: api-zone

eureka:
  instance:
    hostname: eureka.bremersee.org
    non-secure-port: 80
    non-secure-port-enabled: false
    secure-port: 443
    secure-port-enabled: true
  client:
    service-url:
      defaultZone: https://${spring.security.user.name}:${spring.security.user.password}@base-eureka.bremersee.org/eureka/

---

spring:
  profiles: base-api-zone

eureka:
  instance:
    hostname: base-eureka.bremersee.org
    non-secure-port: 80
    non-secure-port-enabled: false
    secure-port: 443
    secure-port-enabled: true
  client:
    service-url:
      defaultZone: https://${spring.security.user.name}:${spring.security.user.password}@eureka.bremersee.org/eureka/
