server:
  context-path: /registry
  port: 8761
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port

bremersee:
  tomcat:
    connector:
      ajp:
        port: 8762
        proxy-name: '{cipher}AQCTgxkFSWHeZFs0QpXk7BakC34jsUOROemajWobujPSuFUg3+SQMVI0T2IJ2F915SxLdKxyEIwqJXn1BNQ5G5rmGklmH/KPqwaWONcpEZUyeVcWWjNvB0jY3W46XOgVZMOiXFzW5kZFRicUwOwUghIO1heuwbVdAXClLn0kxCu+E4LdsBkDHD8IqXKBSaauJaUupK8xWAbIudlHi/TSMGLbWtd26cTcaSwavwN63qn3WswHiRx4FeadTkKuvkx+X8o/gORFbdfVEw6Z+L0LiKLhUoBC53YIFclmVD03GWE1vuGfC9+1trCzlQFMaFX4FLApqyZmTmE1mhPD4+plH5FPRhFDd+AbMLfO+315XqSvGvzpz0DtKNr0bDVBADiOkuSVuudUwacs'
        proxy-port: 443
        redirect-port: 443
        scheme: https
        secure: true

management:
  context-path: /admin
  security:
    enabled: true
    role: CLOUD

security:
  basic:
    enabled: true
  user:
    name: '{cipher}AQBmLsWGHc5T9SVivgvnm5k/wzink75MHW/ymvdv4gTfUqblbG/pXlK19126vgXklVIa0Or4yNMIwXMF0i/sbB+SNZrZyJuVFdsQcdeDhzdkItbwQfkuXpezxjXGbnHKq/bkkeEcBGhJ5L/K3h5s1jFPkS6YCq1O+awAF38BOT1/hpgNhjDHmj/i4aoWKN+o3tVwQzMgg4CdWa6M+rVKOCHCrIVq7Xcg+cD4g1cguO0lf4Ibd5xnNb6kjdZNuy+xClvjPD8thsSNjaQ+WQQ6gNN3MInEL8CcLcwRBWzqHmIpEP6Z503OYN5VAGhgTkeuYfLgZ/LFIkG3u7QQkNaWU9FVUq4O9CNtx6m3HwBYYCrJszFFZ0qJUza9ne/OcxwJ8aw='
    password: '{cipher}AQA4HVyhPvGGWcnF3HUuh0x/uykqYAlmQ1yLmXH6otbRSR5IL+CgT3p2zAIBSSCbVYGs5l8T/rNCh7m9IkDcUKdFESjXCbKo8P6rH7PDUe0BN6aIZH+guWZu5r+F2aZZyGt1pEKGPThRLj+BE5rWtfwc+9PuKJqsCkWe/160euN0YEqcKfdRVMzG5T1bKULmXkXE5E1vgRmcmHPkeJBCZyuINrHqsPhSUnB61z9hdEXCkUpTv9oZpPJC+1DXZNrx+D5r8ne/hIFGM24uW5N+9Fark95f5M2/81O24PI/bK1/0/Fvc4ELiyUrw8aAZhKK1rSy96ccpg/RlnAOjLEjWVjqjbE4tb6UCWSKp4DuhieEfp/nBHYDqchBKnjJIIkGSCWX2s9MaEuWms1i4ZrOuZZ/ZAC/2KCXxDmS7YDM+X0rE0uq+k70qk2gIFZMC7xlaiiJhk8VbhlJbQucvlZgQIuu'
    role:
      - CLOUD

eureka:
  instance:
    hostname: localhost
    home-page-url: ${management.context-path}
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}${server.context-path}/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
      
---

spring:
  profiles: devel

server:
  use-forward-headers: false
  tomcat:
    accesslog:
      enabled: false

---

spring:
  profiles: base

server:
  use-forward-headers: true
  tomcat:
    accesslog:
      enabled: true
      directory: /opt/eureka/log
  
