bremersee:
  actuator:
    auth:
      jwk-uri-set: ${spring.security.oauth2.resourceserver.jwt.jwk-set-uri:}

management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95

---

spring:
  profiles: swarm
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://localhost:9411/
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:unknown}
    instance-id: ${spring.application.name}_${eureka.instance.hostname}
    non-secure-port: ${server.port:80}
    metadata-map:
      user.name: '{cipher}AQBtTH9N2P5gRb1w27Snd4O0eben9jBkpWvLcaq8XO2MIO4O22tsNiQUIKBwYV6FulzQvy5hV5yRthjkgznJ0U6YzZB86WhijHxDG39fJ33OBTrnDid5MBMnDtE1TDbNz5QQwKrLgGsY+sNfXwyrAtpivPsk3yq0NxJDaqm5Dcix5M0oxAr4qyBQ4bVf6D/NuXb4hmWJtsa+yFI6gwsZimvVKVJaks4n6ruGEaJzgZuaCcAog2YtgF6B3v2xIaoKfyoRD2BwrfE+w4Hwy7Z0DjHxNFpQv6P1zJEUuqks/tuadhYSjxsUFB4ZHD8vfB1hyRQZbAcwvmJEwY2RoxuI4cUcD16byfFutq70WFISnl3ZeC9ebQBEFhuMiCO7fp9NryE='
      user.password: '{cipher}AQA+8KzLCa8EvZiGfF1089gugs09TduEFNy4d8QhCOtmKcly+sBM9HWPusazZjkDHE52m6tznRip4Wkcv9LbRvsevnZK0Cq3SkxB55ZTM+Mn0WzZMO9NEYv1H2DcX+sD+Ykr7RBuZTU1uYKvOMe+TpR24LBkg/Aa+1/xFdcrRwtNY5jRTCoUpzxI2ECT0zS/NL/21zuDBgj9QrPyHWUXVHd29icI4klF+pRfyCZrzx5J9lrd5lMQqU6eUfwPlfCGiKMdxftcINOXtkKywcBt+9LuEWQQTRKze1Vws9N2Hm2A0aQa/+0bgsmZcJ03i9saiHdyztj4PHnC9XxdkThfSlIslI/Qw7bLSRRHDAiv18rgxfytz8eiuytV8zOQW6IBByY='
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: /opt/log/${eureka.instance.instance-id}.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  endpoint:
    logfile:
      external-file: ${logging.file.name}

server:
  forward-headers-strategy: framework

bremersee:
  actuator:
    auth:
      enable-cors: false
  cors:
    enable: false

---

spring:
  profiles: ldap

bremersee:
  ldaptive:
    enabled: true
    use-unbound-id-provider: false
    ldap-url: '{cipher}AQB+foyajAOpFFQ3s9/jmCRoZiNiOKw7FSaA7zbWxCAG40i9WUZZKi5aCzkW/KGqmhi8jDx+A7LrjOqq5ZmjdqlOSh0JNxMRBl9e+8Rd2NsyhUHVGunNwQR0B49ZLb/EEecKedgD8Q1o+eU6tnvWpERPMJpUs4V4XQHhhemyBN3bRvZ8UsT5Bjwq/hHP0VNJTS6jw4eYu8RFZCJrsm5ks2o8hpcjWb+f0VgR1Y/WrFoYVpZW+fI7CwA6lyGRb42JR5n7eXpD59lRaVwv7l+kF5ou1TSPbeylGXxrh9KpdWqz/sBA80pb0BA644zc4dNJldhAIFqWpXL1d24p4nXhiPcbzU5bDcz/H5/Xyj+qABJSFfCMLmhZWy7kzNRpAxjIzOcdwMzcKRJ25JvFVH75WWjRsYIfWgyT24j8RAU74mYqblSHuLmhbTdCM9vpZkgiCZHD9ntX6jHq0VSPxbfoNaR6'
    use-ssl: true
    use-start-tls: false
    bind-dn: '{cipher}AQBAyUg8HKpK2KNQxr89z/3tnpEuVuT4+2kbdgNq/ezxdi0254pRXn0GNOjTkIOT01tMrKPUcUBgZj/1WFkSuBD7H3Q0WR/tYMT644pZzwC4Jpn/j8SWRcHqJKDAq72W3tbVdOzG7v0mu+29hY6qcVx8/9+cZPYyScLz4CGUvSIx+xq1Hlv4hIbixvVCOPzJWoTpTuqGrYwXu0O3G1Wru+GhK0tfRlwnCbKyiac4yIa+HBAahMV548+oQqiD7AXXp6BDYIODo7kBBsQk3aFWIu9PdFZKeQrXgQ7zZ8SS0HPJ+mESt96nT+xDkur5PgwnmQUc6mEoNDGCoQBRpMEseAaS1HjiJCPs/ry9IyRtj1n9vLmkuTXHNc6351NtKZy4s4T6n+hA4zJdO1Gas4CPPJvPRjzNeLye78UiKXlR43X96g=='
    bind-credentials: '{cipher}AQBFsE6aRbmoiZfWYqR80BKl6mLOgB58tJ82RaKUScgqnNBXW+qBoXzkNwiQfWbahH3lGWRsV6QgZJOyXBWP0tB5ePRAhJCZcRi67zVyBXzqlvAXGn0RF97Qf260yBKoBVFrdEcGUODruuG0vb9SiGfLuxhSxhE0iGl4ubhWucDnS8bKiH3wW6qB0t7HYfHsHg/YkIgZDD0vgOpvAG+7ckIR9NXsH6LPCf4ai80KVC3ShPD8/gMGhv6DrSLAHoItxyO0u//Kb7iRPaVLvFh4RWd2KVhAbzeQAR3xYKLUkJGkpGd1WarKGDbkB2THaM6s2PL3toIwMMka6L7gYYj4GIIsJNZ3EDswKcDdpYcjZ53nGb1ZLF7ZKcYFKzOiHNPW+nZFpMZN7Iz/GR7OXj/Q/hP1'
    pooled: true
    min-pool-size: 3
    max-pool-size: 10
    validate-on-check-in: false
    validate-on-check-out: false
    validate-periodically: true
    validate-period: 300
    idle-time: 600
    block-wait-time: 10000
    search-validator:
      search-request:
        base-dn: '{cipher}AQCkR8AGNdk6bICBa7h79sYDpW7bNTl7vMpm0BxlDj2b38CdjbaCKdK5BU9aN5K1N+ol1a2gkXw2mcdUMQHD9CPIbr2/VAQ/glvha9zo/AuAOagA0pKXITvsH/ouQ6MyhNKw0nNdlqWVvfaj01yigpzkJW5db2NutD/5YwwgLo/5FP6WSWFN6blaU9xEdgRNGI6kZpkq+Ks/l0EYYqACr/0jtb4ra4KpoOena/IjsKsn+N2lU11yWaMjrQ0PbBKENUN6baKQFhH9Y8OE9UHx5IAWNmqGB2V2i2QLB2Y4mtTEX6azaiO58qlrZtea8ftbPa2rtEHMWqaVpAYWyFG0a6f3xu99OtFOzVKMcjs2NVDcAtgSFgPRrF5NakeTLbqS/VlUqrZgehva1N9uBbUY31sDzh1n1cgi5tVqfNC1nHyJqA=='
        search-filter:
          filter: '(cn=Administrator)'
        size-limit: 1
        search-scope: ONELEVEL
        return-attributes:
          - cn
  domain-controller:
    group-base-dn: '{cipher}AQBzcR5wqtrTPMinMCauElYfv0gIrssuefcqEyEDRvRLjlO7xBFwiPaoTQqSSLjaHi9hfFp/e2a/JDQIondWwXjDoXclP07lku8MW/HUyI8ekM/ZThuCLKbXo9X8uQu6qlRxn+LegifqyW4acypKlyN1ayRJYbZ9D71225FJ8W1myRaslAIripY7X1jmosHvHN8s+brK4vdWvqv1Im/OBSITq2kpELre3ncdYGs3lSZ0HR6s/Ygxr8pFd9uNpV2xlFTur5pNeF1CTc7g5vqpMRLrBdSxNR2WIN7ilI+pMiHcGNvsieYJ7Zrvu0mdMpmha/n1Lvz7lChaTyyL7QZMHg98Qbl/IEJdBj/IZsL0XBMkc3yn90dCS4BlKwkudBMzNY3RiqvOmr+niiyaO92TqAmoucxcooe0rniHyN2gTrEHbA=='
    user-base-dn: '{cipher}AQCwRh/8z7UomaFJ6cTregkGjtLrWgskasEol7M4ahCeDJuqa098m9B+iv3cI4TurFbHr8B04o0on1dwBhnRcDjET0qGWr1Njsu7gwyu2arLmFBUyfbaE8+NU5vGLgLYPKoA4ZpvYWdufGMcyXYz3dZOM1qy4W/zBUBWaibbhXMNi/Sa9l/4ysL9ObA90LXpbaSUtp5Z3QPACzV93CMdqHtzlfe7ha56HEPYYQTo5XUFvKbAncCgLfVGPYCc2xcEygYQaVbxRt2+N4fMjGU2O6uSELY86CXrs7OuevMvWc8OAc2GghQUY2kPdRHpJsViWSI/MafUhngAofYr8Ln3LV62IqJ3mCkVnsqDdO5U2ehvWW1iC/BdRbrxuevg/7+WH0niRXV+p8t9H0mCs7fB0o11rbG4R/8MQAOGPAlkjzmr5w=='
    admin-name: 'Administrator'
    ignored-ldap-groups:
      - 'Allowed RODC Password Replication Group'
      - 'Cert Publishers'
      - 'Denied RODC Password Replication Group'
      - 'DnsAdmins'
      - 'DnsUpdateProxy'
      - 'Domain Admins'
      - 'Domain Computers'
      - 'Domain Guests'
      - 'Domain Users'
      - 'Enterprise Admins'
      - 'Enterprise Read-only Domain Controllers'
      - 'Group Policy Creator Owners'
      - 'RAS and IAS Servers'
      - 'Read-only Domain Controllers'
      - 'xxx'

---

spring:
  profiles: dev
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.7
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs
  data:
    mongodb:
      uri: '{cipher}AQBxQ1zlu+amMiwD/7JYbjkikIkHXPd7UtNdtMaktBCwpniCW56iw7Kb/GFpe0J3r5K0JmUGNcR9bEAAHaqwzy+dhaPWPJcdmE+qFmBss/UBIDg77pEhulmf0EjeqXF1afrLxj3h+vb+QgAnxDgwjhPv0imR0MjGz5dhX0VW/LIuujcDC75vdp5CY6HNyjekCT440UUhy08Y14Nbhc3Zwz9E/d9b/T9dSbOcR3uccKYPE8FkyFPYCqLeXuHuaT59DqLdbyhV4eEFOfJ45S1KtECFVoVKL6t4Fu42awdXYWG1YHCixb/M3MgrBl7WS9eW5UoeUtKzXCwCGyEVYqWK+Ee+Au13/OZXa3R1HfXR0rzme8eFsZrRbC3Oa8cb5aI6Ginzk80JTIUIcDBSfReGOw9BKcX9s1PD7eMaQJri0ZlaYKcQy5TUlg+QsX0LHHRQ/s7+tmEMLyUfGVxve2nZlI3BkB4y2G79wC+f78wES2xndr5qWI15c4ttmyy3LwL4l25ic7UkYmmvNI2q2Ppbm64M'

bremersee:
  auth:
    eureka:
      username: '{cipher}AQBWGFbNNMTwWBU5Pqf9M2C5I3sazPDF6qPpVTCGhKtsvEHPBleMD3mYUfDwCFzZEgDoHEjjW1eVILrib+S1JrNbOwdkkg8QY7S1DgOEeiy6qNHUspI8j5bMCvoYkx/m0umGh6NfOUNCxk34PDjF6hH9K5kppRhAANUeLF/vtji/NF9WRl0jrmf79aHUyxVvu87Vpd70KdlP3s2UhADa5b6ePwLWwcfczQX5ibxnobXEaeOoPNFaKOXoC9SG7BACsgT3KPW0DIfu/GXi/skbAg0QZnvRn1uBYIXfkf8ix//lZFZ57M2WQDcHgdHlNf+/oOoo7IoTT4kjKuIwzUd9EK+aJYRtSez8VFk/rk+vG4E+UShfveH9WbJHY4UzIlWuNu8='
      password: '{cipher}AQBSTXFR5pCi01YxMJ7APS/OHt+dopgHHaKjl7irWamHxXYbJixsccArznT+LNWKzJoAYcx98KLoLVyMLbTs0HkS9ru2PnkvsWmhgnwcfcQwysTyxLNba/2NOIT6riujcvggJNxFhkT0iRhuF4Hk74gK64DBqYxbi99voGMQC6OI4FDYBb8ci6UxZsIVTkUYLHPv2nW9ympf/wUlgp2GBJh0IsCYQztXF1pTTlKXGly+Q6VlhwNlFZvQSE6jri17ANUoAG78247DIoDc1U/8OsHViVCcTVJA/Nl+D7fey7s99qAQBtzFW0Lz7rHf5wNn2nIUeCul9+ai9afWlF7m8iBGW/JhtNXf/9cRDc91jKhGfwqin48OYYnb+8oRkD/plWzw84e32c8SK6qr7D/aGri9'
  actuator:
    auth:
      password-flow:
        client-id: '{cipher}AQCF/td/4+X6pRBSjO6gGyYu2pA0FFBcEYNMJw7hUu1WW3JXuLzJKg6gKYdaK76exGLmcGr+8DXXbTaU7mJ8RKNeZbWw9hN5H/gt95E5oRX6D1qRe0+/z4k/VDthPppTeaL0Z9/fMhvmn+olSDY1x0OKBtb9sH1MpaqQcm0HpKsp7hisCLjyIubpSScikTrCpylyFT3EK/TcUSbto8QlZvkAESHGcJVYInO4OmdrO/ccJAxmDJFpJj9SwRDzvzi0wgxIzFjjcGbFhkvbSrcC5wB/DDxp7cHpk0AbUw709cFlMdGH7wXQmJk1g7ew1xIctn6JtWE7D+L1yxFMeOUia57bPUNS8tkrXRCHGy0c3ltX5yaGGU+n4eTSmrnsj6OoLvc='
        client-secret: '{cipher}AQCxXnCOHLoWSmvEFMWwqo7htS7FIGr7oPBwV96mrfQYCJOugIZHrhpvUd4ti+iPJYYC0CFqJUjHDRkbcmVVkWZPAgRGfdknLz9MUm54R1tjMN3nDAG5ke0FxugbDcES8JjG3NSVxlTHF3Jqp17vVsfJwa/iSPo3ugaAR0ZDwZ5bIl+GJDG/7Bd9egkDkbpNvfttuce1OzPUmlpOMJR5SbsVC8rQP4kYoTHhyEhIJn9nEPQ23dT+IsXrLjERbCDU5YXHmMGyQWhNhZD7DbRcbN7rVRgKmlQhpstLW/U1bMI6ifHiELGAB9e3kHiCEH6v45i6l4MOiHXmvfTopexTpH+gN/HIGF7vaz33GTZwtDBbFEo+TFWMt3VOlIDXM+O8UxAfhi5yX5faWEKJWJ5rshl4k2576ZVF6ZpeR+8iW9DGUQ=='
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka1:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka2:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka3:8761/eureka/

---

spring:
  profiles: prod
  cloud:
    inetutils:
      preferred-networks:
        - 172.16.1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/certs
  data:
    mongodb:
      uri: '{cipher}AQBwaZYcE+wo/HDVX1jAWXKomwwC5gXZLRwIRzlXkE2x40RzBFK0sjwrZXayk633lY29asZixpf7uRmcsS8wfukIw7lLuE6KIr2rNnslJUCX5uRqISfHIKPY7JbismUAXvr+xusJDSfsdvxJyMs44i7CHxBSRTGNOl2+RznSLWxXN8xp1wj8aukNAUlE0JHRc0POaza7NL4ZUcx8esxYtsOZmwrOiwbPNx2rhdxtg0dfWDbMt3BU2+fA8LBsAPXriRQkhwMnzGfhydaqQRQ5ibi9+33VYAay7Ig/VTnfG3kK5bPw9Ebr9BpvgDfsYvZdKO2fnzlXrKPOSpLKmxDnCo0n5VBXkh+XAaXNQHzoZe6GFfHp/FGznPmCNqnbe86Ceg/wPVVE488QWD+Kf1A8arE1GIQ4b5U4wwYnopZ98w4Xhwjc0uk9SmRUx1OL9jfcHjh+Oms0I15M7rmR4Ctn+uAKua6UIAV1oN5qwk3OPt2+J9tRl1KeP250btHkL53J0q+LIBwgtF1GbJe6XEXmdqzy'

bremersee:
  auth:
    eureka:
      username: '{cipher}AQAs/zyqDN6WusLJP5Lu4P8JK13EPMbvVJt01OSbbycBsGW9SQ/GChI51LMLLV6+TOjnGDLVqFBxHT06s37ugAIzPS9UlDtsNRsUx2hWyDsYW1AIH9dV1ikijuNgg3edTLJOJ2RhJkXmdb9+q3sdAMgBmOxQafbOftAvRKlhfBLkviYJG9Nv8Pi3P6RDP6eyCs8119wIv3LWe2BVJbLbo9Xn8FTAM8yC8a3D1SIG48J7stDWDln4WPDax8Tc/w4Qvrn3/y2fIIr+uSye4gXOaLs5YbqQTVtqGwpBj9eB/H6pSCOuxhj+plKP9cl13VIA31lEvJWzKAFOK8H//rI10cwcXoI7Ev7AEMKke58kifAvUyhPjLQl7Px6hhf3FB/TqM0='
      password: '{cipher}AQAgP5Z8+CWJX/sy5g9yF4qmCMSxfn6BfvXellyt+SXDLins5BSiRac7ppOD8bdE7g7QGD+GFyYjYYbWVEJdjtRmgGh3GIvOJNrIHzS8LF7SsyebpTP64Lc0hOgkH3RVOEtngItXTortn85FyVieYkQaP20ssHrYMSHvhaYYxSuBuFE2XTwXZMlg8Wvz3yW2hHDVMlRgz+kRZgc5P0COJbtjOXn0yR8MBB6CyzLjgG4Ul657rQZEPNgv+fduDxGvseK0yAM1XFBpfDLBlD5nCGO3w42b1UtR0LplK5SQH8WbD6NMYT4LA8SAUQDx4Q0ATNOnn14Au1GKzfZtflCKGbbakhG+BG/IrzvzNa/gjQxEkfx5+bvDx5jdIVqiD4c3T+V1v/OQgtIF+/7PeZK/3dL+'
  actuator:
    auth:
      password-flow:
        client-id: '{cipher}AQCF/td/4+X6pRBSjO6gGyYu2pA0FFBcEYNMJw7hUu1WW3JXuLzJKg6gKYdaK76exGLmcGr+8DXXbTaU7mJ8RKNeZbWw9hN5H/gt95E5oRX6D1qRe0+/z4k/VDthPppTeaL0Z9/fMhvmn+olSDY1x0OKBtb9sH1MpaqQcm0HpKsp7hisCLjyIubpSScikTrCpylyFT3EK/TcUSbto8QlZvkAESHGcJVYInO4OmdrO/ccJAxmDJFpJj9SwRDzvzi0wgxIzFjjcGbFhkvbSrcC5wB/DDxp7cHpk0AbUw709cFlMdGH7wXQmJk1g7ew1xIctn6JtWE7D+L1yxFMeOUia57bPUNS8tkrXRCHGy0c3ltX5yaGGU+n4eTSmrnsj6OoLvc='
        client-secret: '{cipher}AQAlCF4Sq+IIiJBba8akT7YfwDZ6lWDwjsKn7m4XFCDO4eU/kQpGyJex4weMMnEy6qTw90IjeaRdARKi9KuXxB8nkA8lHhXnaeD0mRDinSfqLzJPD0xWSBXNHOGQ9U9YY1TuIpc5zBlxBzzFRfw60RyM/rYyjxmjx6P5mExbaakypp/JL58XZ2PkIehxug9xI3jtxZ8krMQJr6LllWkpT+gx/FCO5fRTVxZAmU10PsZSYgjWgJaNGkwPppEqNiERav/1+5BDvsUqVnV7xODRIEchgvd87ByBSrTfuKEA9XvAjWhsH7stblhVLvPfZeybRZ1pGs2LApw9TAP3laFINwwSOln/wKS99alVsR5WYpMrQ1W2y5juLmbPhOdx/mv0622hUe4rR+g40hlvtUiddIDy2TTJKlWjFZHMN3gZN1pweQ=='
        token-endpoint: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka1:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka2:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka3:8761/eureka/

---

spring:
  profiles: local
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs
  data:
    mongodb:
      uri: '{cipher}AQAi0S0YK3xXoT8Mt4tKnUNXBZ0ho2HKfQQoXWvd1KXTFnCDsVgi4BJ7bG4y9VnONx89Nw2TThQxjF+0PdZtGpwKYYJVFixd63MhruEProUkSbdHXPayHCYx33rYowg1z7GI0mxuJ3euDOaOOy7kpTMpC7ZQJ2+wqBi7EYeDVKmji0V4NVnhtYjgDFbPGymvj/GXN6/Pgfud0AUD4jWTe1XR2q7cU6r3W+6dlMF3Q5fygNrz/29VJpoeUuC3bqjKeFoe6V1BQXZr8BdhuMx92fvi/KORKiVwPmb9HqMC0ZultRfOfokbZ/Nn1G6cEvp5wWU4V+AhE/5VUr04weaG67Z/Cqd8heffpptk9ISpS+m256s236sOaoJwZFvVmhz+4R6IlPPUllLQq6EisD5Rar6hfXlg+rjfcOUjq97VkoxurmBExDKT1TkapzRryo/3f5ZnuStZQ6fPtDbpO7v0ckhd6bsZKidnGjjcH/zIZMTUKQ=='

bremersee:
  actuator:
    auth:
      password-flow:
        client-id: '{cipher}AQCF/td/4+X6pRBSjO6gGyYu2pA0FFBcEYNMJw7hUu1WW3JXuLzJKg6gKYdaK76exGLmcGr+8DXXbTaU7mJ8RKNeZbWw9hN5H/gt95E5oRX6D1qRe0+/z4k/VDthPppTeaL0Z9/fMhvmn+olSDY1x0OKBtb9sH1MpaqQcm0HpKsp7hisCLjyIubpSScikTrCpylyFT3EK/TcUSbto8QlZvkAESHGcJVYInO4OmdrO/ccJAxmDJFpJj9SwRDzvzi0wgxIzFjjcGbFhkvbSrcC5wB/DDxp7cHpk0AbUw709cFlMdGH7wXQmJk1g7ew1xIctn6JtWE7D+L1yxFMeOUia57bPUNS8tkrXRCHGy0c3ltX5yaGGU+n4eTSmrnsj6OoLvc='
        client-secret: '{cipher}AQCxXnCOHLoWSmvEFMWwqo7htS7FIGr7oPBwV96mrfQYCJOugIZHrhpvUd4ti+iPJYYC0CFqJUjHDRkbcmVVkWZPAgRGfdknLz9MUm54R1tjMN3nDAG5ke0FxugbDcES8JjG3NSVxlTHF3Jqp17vVsfJwa/iSPo3ugaAR0ZDwZ5bIl+GJDG/7Bd9egkDkbpNvfttuce1OzPUmlpOMJR5SbsVC8rQP4kYoTHhyEhIJn9nEPQ23dT+IsXrLjERbCDU5YXHmMGyQWhNhZD7DbRcbN7rVRgKmlQhpstLW/U1bMI6ifHiELGAB9e3kHiCEH6v45i6l4MOiHXmvfTopexTpH+gN/HIGF7vaz33GTZwtDBbFEo+TFWMt3VOlIDXM+O8UxAfhi5yX5faWEKJWJ5rshl4k2576ZVF6ZpeR+8iW9DGUQ=='
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
