spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT
  sleuth:
    enabled: ${SLEUTH_ENABLED:false}
    sampler:
      probability: ${SLEUTH_PROBABILITY:1.0}
  zipkin:
    enabled: ${ZIPKIN_ENABLED:false}
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411/}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OPENID_KEYS_URI:https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    ROOT: info
    org.bremersee: debug
    reactor: info
    org.springframework: info

bremersee:
  security:
    cors:
      allow-all: false
      configs:
        - path-pattern: "/**"
          allowed-origins:
            - "*"
          allowed-methods:
            - "*"
          allowed-headers:
            - "*"
    oauth2:
      password-flow:
        client-id: ${OPENID_CLIENT_ID:omnia}
        client-secret: ${OPENID_CLIENT_SECRET:changeit}
        token-endpoint: ${OPENID_TOKEN_ENDPOINT:https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token}
  exception-mapping:
    api-paths:
      - /api/**
    exception-mappings:
      - exception-class-name: org.springframework.dao.DuplicateKeyException
        status: 409
        message: "Group already exists."
        code: "GRP:1000"
      - exception-class-name: org.springframework.dao.OptimisticLockingFailureException
        status: 409
        message: "Version is not up to date."
        code: "GRP:1001"

---

spring:
  profiles: ldap

bremersee:
  ldaptive:
    ldap-url: '{cipher}AQAP2G7Qn7fQdyTxb2Rwi6XVYla4J1OsqvA34E55s625gZNPtRghIA82O/jp7rKNvDb2M7pkP7mwSAmIJjiIx03RUFDBaTmZAm//Z6cvGdkSyV4dw0/z81FfLytlEFLrY7K0tgWYsSY8kI4Dvs5Co9EYjIi9TfqUVmTC3wlr5Bg7JGN86GKrI3eCQYYLQzyBCnjwuMYHd5XPE5JPQAiV8xWFgElM4DVAKTIxF7Xy8V2x/U9macuFI3rgDrOahjs8dTWIPGZgoM10UE57YNXIa7mhAVfUJEb/NzsdytEot6qj6EaWtkNhBlnws8fzOC6PTg/hMge5VfBcFdxW0SS3dPJ5vbt//mQ3TCM0hF42u0IXPX5G+YfCyEZFwpkYloWcc9a6Roh4yHmlrSa4ksr7h8seWd0CYSmMa3F1Bzam8nvZkw=='
    use-ssl: true
    use-start-tls: false
    bind-dn: '{cipher}AQBAyUg8HKpK2KNQxr89z/3tnpEuVuT4+2kbdgNq/ezxdi0254pRXn0GNOjTkIOT01tMrKPUcUBgZj/1WFkSuBD7H3Q0WR/tYMT644pZzwC4Jpn/j8SWRcHqJKDAq72W3tbVdOzG7v0mu+29hY6qcVx8/9+cZPYyScLz4CGUvSIx+xq1Hlv4hIbixvVCOPzJWoTpTuqGrYwXu0O3G1Wru+GhK0tfRlwnCbKyiac4yIa+HBAahMV548+oQqiD7AXXp6BDYIODo7kBBsQk3aFWIu9PdFZKeQrXgQ7zZ8SS0HPJ+mESt96nT+xDkur5PgwnmQUc6mEoNDGCoQBRpMEseAaS1HjiJCPs/ry9IyRtj1n9vLmkuTXHNc6351NtKZy4s4T6n+hA4zJdO1Gas4CPPJvPRjzNeLye78UiKXlR43X96g=='
    bind-credential: '{cipher}AQBFsE6aRbmoiZfWYqR80BKl6mLOgB58tJ82RaKUScgqnNBXW+qBoXzkNwiQfWbahH3lGWRsV6QgZJOyXBWP0tB5ePRAhJCZcRi67zVyBXzqlvAXGn0RF97Qf260yBKoBVFrdEcGUODruuG0vb9SiGfLuxhSxhE0iGl4ubhWucDnS8bKiH3wW6qB0t7HYfHsHg/YkIgZDD0vgOpvAG+7ckIR9NXsH6LPCf4ai80KVC3ShPD8/gMGhv6DrSLAHoItxyO0u//Kb7iRPaVLvFh4RWd2KVhAbzeQAR3xYKLUkJGkpGd1WarKGDbkB2THaM6s2PL3toIwMMka6L7gYYj4GIIsJNZ3EDswKcDdpYcjZ53nGb1ZLF7ZKcYFKzOiHNPW+nZFpMZN7Iz/GR7OXj/Q/hP1'
    pooled: true
    min-pool-size: 3
    max-pool-size: 10
    validate-on-check-in: false
    validate-on-check-out: false
    validate-periodically: true
    validate-period: 300
    idle-time: 600
    block-wait-time: 10000
    search-validator:
      search-request:
        base-dn: '{cipher}AQCkR8AGNdk6bICBa7h79sYDpW7bNTl7vMpm0BxlDj2b38CdjbaCKdK5BU9aN5K1N+ol1a2gkXw2mcdUMQHD9CPIbr2/VAQ/glvha9zo/AuAOagA0pKXITvsH/ouQ6MyhNKw0nNdlqWVvfaj01yigpzkJW5db2NutD/5YwwgLo/5FP6WSWFN6blaU9xEdgRNGI6kZpkq+Ks/l0EYYqACr/0jtb4ra4KpoOena/IjsKsn+N2lU11yWaMjrQ0PbBKENUN6baKQFhH9Y8OE9UHx5IAWNmqGB2V2i2QLB2Y4mtTEX6azaiO58qlrZtea8ftbPa2rtEHMWqaVpAYWyFG0a6f3xu99OtFOzVKMcjs2NVDcAtgSFgPRrF5NakeTLbqS/VlUqrZgehva1N9uBbUY31sDzh1n1cgi5tVqfNC1nHyJqA=='
        search-filter:
          filter: '(cn=Administrator)'
        size-limit: 1
        search-scope: ONELEVEL
        return-attributes:
          - cn
  domain-controller:
    group-base-dn: '{cipher}AQBzcR5wqtrTPMinMCauElYfv0gIrssuefcqEyEDRvRLjlO7xBFwiPaoTQqSSLjaHi9hfFp/e2a/JDQIondWwXjDoXclP07lku8MW/HUyI8ekM/ZThuCLKbXo9X8uQu6qlRxn+LegifqyW4acypKlyN1ayRJYbZ9D71225FJ8W1myRaslAIripY7X1jmosHvHN8s+brK4vdWvqv1Im/OBSITq2kpELre3ncdYGs3lSZ0HR6s/Ygxr8pFd9uNpV2xlFTur5pNeF1CTc7g5vqpMRLrBdSxNR2WIN7ilI+pMiHcGNvsieYJ7Zrvu0mdMpmha/n1Lvz7lChaTyyL7QZMHg98Qbl/IEJdBj/IZsL0XBMkc3yn90dCS4BlKwkudBMzNY3RiqvOmr+niiyaO92TqAmoucxcooe0rniHyN2gTrEHbA=='
    user-base-dn: '{cipher}AQCwRh/8z7UomaFJ6cTregkGjtLrWgskasEol7M4ahCeDJuqa098m9B+iv3cI4TurFbHr8B04o0on1dwBhnRcDjET0qGWr1Njsu7gwyu2arLmFBUyfbaE8+NU5vGLgLYPKoA4ZpvYWdufGMcyXYz3dZOM1qy4W/zBUBWaibbhXMNi/Sa9l/4ysL9ObA90LXpbaSUtp5Z3QPACzV93CMdqHtzlfe7ha56HEPYYQTo5XUFvKbAncCgLfVGPYCc2xcEygYQaVbxRt2+N4fMjGU2O6uSELY86CXrs7OuevMvWc8OAc2GghQUY2kPdRHpJsViWSI/MafUhngAofYr8Ln3LV62IqJ3mCkVnsqDdO5U2ehvWW1iC/BdRbrxuevg/7+WH0niRXV+p8t9H0mCs7fB0o11rbG4R/8MQAOGPAlkjzmr5w=='
    admin-name: 'Administrator'
    ignored-ldap-groups:
      - 'Allowed RODC Password Replication Group'
      - 'Cert Publishers'
      - 'Denied RODC Password Replication Group'
      - 'DnsAdmins'
      - 'DnsUpdateProxy'
      - 'Domain Admins'
      - 'Domain Computers'
      - 'Domain Guests'
      - 'Domain Users'
      - 'Enterprise Admins'
      - 'Enterprise Read-only Domain Controllers'
      - 'Group Policy Creator Owners'
      - 'RAS and IAS Servers'
      - 'Read-only Domain Controllers'
      - 'xxx'

---

spring:
  profiles: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs

  data:
    mongodb:
      uri: '{cipher}AQBxQ1zlu+amMiwD/7JYbjkikIkHXPd7UtNdtMaktBCwpniCW56iw7Kb/GFpe0J3r5K0JmUGNcR9bEAAHaqwzy+dhaPWPJcdmE+qFmBss/UBIDg77pEhulmf0EjeqXF1afrLxj3h+vb+QgAnxDgwjhPv0imR0MjGz5dhX0VW/LIuujcDC75vdp5CY6HNyjekCT440UUhy08Y14Nbhc3Zwz9E/d9b/T9dSbOcR3uccKYPE8FkyFPYCqLeXuHuaT59DqLdbyhV4eEFOfJ45S1KtECFVoVKL6t4Fu42awdXYWG1YHCixb/M3MgrBl7WS9eW5UoeUtKzXCwCGyEVYqWK+Ee+Au13/OZXa3R1HfXR0rzme8eFsZrRbC3Oa8cb5aI6Ginzk80JTIUIcDBSfReGOw9BKcX9s1PD7eMaQJri0ZlaYKcQy5TUlg+QsX0LHHRQ/s7+tmEMLyUfGVxve2nZlI3BkB4y2G79wC+f78wES2xndr5qWI15c4ttmyy3LwL4l25ic7UkYmmvNI2q2Ppbm64M'

bremersee:
  security:
    oauth2:
      password-flow:
        client-id: omnia
        client-secret: '{cipher}AQB8JweoVtCLnpj5fbjSJk+5chSTYfewd9iyw4OGktef73BplB4Qp0br4j33y4koFpWgEknSWJaQC4PB1z6TQQUHKfiut8XnmvJf6LcrT7Jk4fg5dGu6xbwe2QBcs352rv5PgnYg7aWRcxMfIie1ukI+nE46F0nRXv0JxBNMMI1KCRHSjtkNxNAsiWKa4VR3gNzPCg3HXbh0xzvJcKu/tkiQbzgZhcF3uuaX0Wl99c2oCwwqfg9nvZy+0v7hlb86bES9DbkCtVG1WiDIG86MSn4gSXk0NrxWux0XlZRdgxNCgZ1IHr+X3UWtpbyiZ58T69AkWD5FmvI89cEWwqnhnqHlibjwbLPM5WXhnKSm8gcZnivAx1r4M0tX0TL3v46+8C0azrJXaL5TwTcn3IBLRk7X5IigQgixQ+5b5VgN5fkuzg=='
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token

---

spring:
  profiles: local
  sleuth:
    enabled: false
  zipkin:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs
  data:
    mongodb:
#      uri: mongodb://localhost:27017/groupman
      uri: '{cipher}AQAi0S0YK3xXoT8Mt4tKnUNXBZ0ho2HKfQQoXWvd1KXTFnCDsVgi4BJ7bG4y9VnONx89Nw2TThQxjF+0PdZtGpwKYYJVFixd63MhruEProUkSbdHXPayHCYx33rYowg1z7GI0mxuJ3euDOaOOy7kpTMpC7ZQJ2+wqBi7EYeDVKmji0V4NVnhtYjgDFbPGymvj/GXN6/Pgfud0AUD4jWTe1XR2q7cU6r3W+6dlMF3Q5fygNrz/29VJpoeUuC3bqjKeFoe6V1BQXZr8BdhuMx92fvi/KORKiVwPmb9HqMC0ZultRfOfokbZ/Nn1G6cEvp5wWU4V+AhE/5VUr04weaG67Z/Cqd8heffpptk9ISpS+m256s236sOaoJwZFvVmhz+4R6IlPPUllLQq6EisD5Rar6hfXlg+rjfcOUjq97VkoxurmBExDKT1TkapzRryo/3f5ZnuStZQ6fPtDbpO7v0ckhd6bsZKidnGjjcH/zIZMTUKQ=='

bremersee:
  security:
    oauth2:
      password-flow:
        client-id: omnia
        client-secret: '{cipher}AQB8JweoVtCLnpj5fbjSJk+5chSTYfewd9iyw4OGktef73BplB4Qp0br4j33y4koFpWgEknSWJaQC4PB1z6TQQUHKfiut8XnmvJf6LcrT7Jk4fg5dGu6xbwe2QBcs352rv5PgnYg7aWRcxMfIie1ukI+nE46F0nRXv0JxBNMMI1KCRHSjtkNxNAsiWKa4VR3gNzPCg3HXbh0xzvJcKu/tkiQbzgZhcF3uuaX0Wl99c2oCwwqfg9nvZy+0v7hlb86bES9DbkCtVG1WiDIG86MSn4gSXk0NrxWux0XlZRdgxNCgZ1IHr+X3UWtpbyiZ58T69AkWD5FmvI89cEWwqnhnqHlibjwbLPM5WXhnKSm8gcZnivAx1r4M0tX0TL3v46+8C0azrJXaL5TwTcn3IBLRk7X5IigQgixQ+5b5VgN5fkuzg=='
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
