spring:
  profiles: swarm
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:unknown}
    instance-id: ${spring.application.name}_${eureka.instance.hostname}
    non-secure-port: ${server.port:80}
    metadata-map:
      user.name: '{cipher}AQBtTH9N2P5gRb1w27Snd4O0eben9jBkpWvLcaq8XO2MIO4O22tsNiQUIKBwYV6FulzQvy5hV5yRthjkgznJ0U6YzZB86WhijHxDG39fJ33OBTrnDid5MBMnDtE1TDbNz5QQwKrLgGsY+sNfXwyrAtpivPsk3yq0NxJDaqm5Dcix5M0oxAr4qyBQ4bVf6D/NuXb4hmWJtsa+yFI6gwsZimvVKVJaks4n6ruGEaJzgZuaCcAog2YtgF6B3v2xIaoKfyoRD2BwrfE+w4Hwy7Z0DjHxNFpQv6P1zJEUuqks/tuadhYSjxsUFB4ZHD8vfB1hyRQZbAcwvmJEwY2RoxuI4cUcD16byfFutq70WFISnl3ZeC9ebQBEFhuMiCO7fp9NryE='
      user.password: '{cipher}AQA+8KzLCa8EvZiGfF1089gugs09TduEFNy4d8QhCOtmKcly+sBM9HWPusazZjkDHE52m6tznRip4Wkcv9LbRvsevnZK0Cq3SkxB55ZTM+Mn0WzZMO9NEYv1H2DcX+sD+Ykr7RBuZTU1uYKvOMe+TpR24LBkg/Aa+1/xFdcrRwtNY5jRTCoUpzxI2ECT0zS/NL/21zuDBgj9QrPyHWUXVHd29icI4klF+pRfyCZrzx5J9lrd5lMQqU6eUfwPlfCGiKMdxftcINOXtkKywcBt+9LuEWQQTRKze1Vws9N2Hm2A0aQa/+0bgsmZcJ03i9saiHdyztj4PHnC9XxdkThfSlIslI/Qw7bLSRRHDAiv18rgxfytz8eiuytV8zOQW6IBByY='
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka1:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka2:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka3:8761/eureka/

logging:
  file:
    name: /opt/log/${eureka.instance.instance-id}.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  endpoint:
    logfile:
      external-file: ${logging.file.name}

server:
  forward-headers-strategy: framework

bremersee:
  actuator:
    auth:
      enable-cors: false
  cors:
    enable: false
  redis:
    embedded: false

---

spring:
  profiles: dev
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.7
  redis:
    password: '{cipher}AQCTSztA3PgRXP1gZTSCqkY5wPkSU6RbBrNYty1d8vd7NaXpbBFXb4eaCgH6R1nkd7Atmgmk5O+ozezlDTciWF7pZaN/IQt/ZkosrgGgoo5OkJ7zuB+zrdk8xr5CGN2fDIuXM6mHDOLt5EM4GnYuIJ42FyEZWCYu5CewgWvDGE59Fdp9/8wLsapbaE96OPgGDkhzGI7u/f7K8aHu+Z1MhTHsLAuFSy4ikBXKYAYdvvEb0izxrp684ME+Hr9l9Fq1/GEcFV7aw2ahoU0H/p35aHoGMYZpbkAqgZTmf3XrkJ8f/eGNgo7BcGwMciVOts3ZS5ezHwRhzngfmN4Utk+pjxHNtIkuNmAQZB1YRCzXGRE8pZ9su/wdL/BuCmE4xeDvoyGQAJJiUOdtNgC0hk6C9vwH'
    cluster:
      nodes: "192.168.1.41:6379,192.168.1.42:6379,192.168.1.43:6379,192.168.1.44:6379,192.168.1.45:6379,192.168.1.46:6379"

bremersee:
  auth:
    eureka:
      username: '{cipher}AQBWGFbNNMTwWBU5Pqf9M2C5I3sazPDF6qPpVTCGhKtsvEHPBleMD3mYUfDwCFzZEgDoHEjjW1eVILrib+S1JrNbOwdkkg8QY7S1DgOEeiy6qNHUspI8j5bMCvoYkx/m0umGh6NfOUNCxk34PDjF6hH9K5kppRhAANUeLF/vtji/NF9WRl0jrmf79aHUyxVvu87Vpd70KdlP3s2UhADa5b6ePwLWwcfczQX5ibxnobXEaeOoPNFaKOXoC9SG7BACsgT3KPW0DIfu/GXi/skbAg0QZnvRn1uBYIXfkf8ix//lZFZ57M2WQDcHgdHlNf+/oOoo7IoTT4kjKuIwzUd9EK+aJYRtSez8VFk/rk+vG4E+UShfveH9WbJHY4UzIlWuNu8='
      password: '{cipher}AQBSTXFR5pCi01YxMJ7APS/OHt+dopgHHaKjl7irWamHxXYbJixsccArznT+LNWKzJoAYcx98KLoLVyMLbTs0HkS9ru2PnkvsWmhgnwcfcQwysTyxLNba/2NOIT6riujcvggJNxFhkT0iRhuF4Hk74gK64DBqYxbi99voGMQC6OI4FDYBb8ci6UxZsIVTkUYLHPv2nW9ympf/wUlgp2GBJh0IsCYQztXF1pTTlKXGly+Q6VlhwNlFZvQSE6jri17ANUoAG78247DIoDc1U/8OsHViVCcTVJA/Nl+D7fey7s99qAQBtzFW0Lz7rHf5wNn2nIUeCul9+ai9afWlF7m8iBGW/JhtNXf/9cRDc91jKhGfwqin48OYYnb+8oRkD/plWzw84e32c8SK6qr7D/aGri9'
  actuator:
    auth:
      jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs
      password-flow:
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
        client-id: '{cipher}AQAPXVwJrflU+IEO1mO109FkvIJBHb7UMdfagdkdVJvmq+dubUT1U1CqK82ALdCqSNMFducNvtgACdQJHf4Mk8UydNSUclOAc0MHhsqx2R5kvQPJ/JdIbU25ucQAaVxGTuEjEtE6PrTpghDonDD+LJW9yTlq7YNvZfPKWZpIj2AUiY0taCDjSFdmi89YbuxUQvQnviI/pwPrOmXrt24+JSSGLY5lj61dqm1dzYx4xMLAuWcBIqm57aqGZpX5CWZpJVvs/qaLPmNXpmxPzvHAVXwvkp3al/W5KxEab5g5ChULWHa7bMquO5+D9KvnF4VFVpJZItEYi17XLI2ChcGKz9VzS3cOy+QByDlcbXGbeVk+QEob8XbiplbXRPhEwR+WCb4='
        client-secret: '{cipher}AQA1fWo37X4XD0ZeSZ019H2MOKT1uwOrMEyjWR7XadZ0Iz8rQccYRW+G2txk07ng3VVMbb9Av5tGf4tt1/li0pdjuSnrH9c14doWDaD8TRMH/lmnbqadHfwXRql03+K6NMLQOC1yhphm/CiZjtedA8wkdnrqzUxouhfncntxywFNctMTSplBK8w7P+Lx1tP7ZpmKqfViwXzzXeriseD6P4g4TYprKhJcJr23VvN3BM/s/ZFCIsr9AgWjPITrSO7+v//DOR+zb2LLhMNcE1kLyh0C4TdFZhNDz+NMB9lxo8j+YhpTXUbALEf2FDoxR+7lCfqMJgg6cKl67GeEumNvzSTsIaoNsq3pqe3JfCcyz4WKDpQIQpoZep2H3B36QRXFXfzt4OYe9RP/kjWTGzIyQlfzCXPFATJ8U/7twV5iribLSQ=='

---

spring:
  profiles: prod
  cloud:
    inetutils:
      preferred-networks:
        - 172.16.1
  redis:
    password: '{cipher}AQAN3SBtcObu2mRWgqu3m+94OEroGqz6d7vZCIZcIKDI0WJAHmuQNXmtHW4zkemnBdpzR0OX2W749Abpk/8E8G5GuKK2E1tCIqDSG3ItAlhjJ6kFGjET0/oOaB2LFIXZNwqAz34Z2tc2OIu+7NtzGywQuLzrr7J8nH0PLjdvdGdAWyH06lxAuW/MsnJfiORW8CBmvsyjFEo2smlHY2jnMZPTEprVGYIJq670O+W1WokxVjjUEIow4zpczRTBiFn/J85UoQduju8aMTxQJEQAVsFpTNj6PBMEbSjVDxZfRqej80UgR9SXBU6z73GWzT6si9K6s2Az4parCKsp1UpB0ubvXFNI8ZddgfXEN7ccUM5JQpFuHA8KTfqylulL9LHxGbliQjrLi5lishbYfcrVQcBc'
    cluster:
      nodes: "192.168.1.51:6379,192.168.1.52:6379,192.168.1.53:6379,192.168.1.54:6379,192.168.1.55:6379,192.168.1.56:6379"

bremersee:
  auth:
    eureka:
      username: '{cipher}AQAs/zyqDN6WusLJP5Lu4P8JK13EPMbvVJt01OSbbycBsGW9SQ/GChI51LMLLV6+TOjnGDLVqFBxHT06s37ugAIzPS9UlDtsNRsUx2hWyDsYW1AIH9dV1ikijuNgg3edTLJOJ2RhJkXmdb9+q3sdAMgBmOxQafbOftAvRKlhfBLkviYJG9Nv8Pi3P6RDP6eyCs8119wIv3LWe2BVJbLbo9Xn8FTAM8yC8a3D1SIG48J7stDWDln4WPDax8Tc/w4Qvrn3/y2fIIr+uSye4gXOaLs5YbqQTVtqGwpBj9eB/H6pSCOuxhj+plKP9cl13VIA31lEvJWzKAFOK8H//rI10cwcXoI7Ev7AEMKke58kifAvUyhPjLQl7Px6hhf3FB/TqM0='
      password: '{cipher}AQAgP5Z8+CWJX/sy5g9yF4qmCMSxfn6BfvXellyt+SXDLins5BSiRac7ppOD8bdE7g7QGD+GFyYjYYbWVEJdjtRmgGh3GIvOJNrIHzS8LF7SsyebpTP64Lc0hOgkH3RVOEtngItXTortn85FyVieYkQaP20ssHrYMSHvhaYYxSuBuFE2XTwXZMlg8Wvz3yW2hHDVMlRgz+kRZgc5P0COJbtjOXn0yR8MBB6CyzLjgG4Ul657rQZEPNgv+fduDxGvseK0yAM1XFBpfDLBlD5nCGO3w42b1UtR0LplK5SQH8WbD6NMYT4LA8SAUQDx4Q0ATNOnn14Au1GKzfZtflCKGbbakhG+BG/IrzvzNa/gjQxEkfx5+bvDx5jdIVqiD4c3T+V1v/OQgtIF+/7PeZK/3dL+'
  actuator:
    auth:
      jwk-set-uri: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/certs
      password-flow:
        client-id: '{cipher}AQAPXVwJrflU+IEO1mO109FkvIJBHb7UMdfagdkdVJvmq+dubUT1U1CqK82ALdCqSNMFducNvtgACdQJHf4Mk8UydNSUclOAc0MHhsqx2R5kvQPJ/JdIbU25ucQAaVxGTuEjEtE6PrTpghDonDD+LJW9yTlq7YNvZfPKWZpIj2AUiY0taCDjSFdmi89YbuxUQvQnviI/pwPrOmXrt24+JSSGLY5lj61dqm1dzYx4xMLAuWcBIqm57aqGZpX5CWZpJVvs/qaLPmNXpmxPzvHAVXwvkp3al/W5KxEab5g5ChULWHa7bMquO5+D9KvnF4VFVpJZItEYi17XLI2ChcGKz9VzS3cOy+QByDlcbXGbeVk+QEob8XbiplbXRPhEwR+WCb4='
        client-secret: '{cipher}AQCIKVQwVZt6hFalvMEcIjkC4KCUkwnzGHuqjRUuaVTq1icw71JQIsqtDKpve7SsY6fmWwuiSLY7byRNEx4TLaBn3gWysm0SdaEmc6XfwXzWPSIZG8tHz1poPEJsHW7xcdq+zPDfxPyp/q/FU4LgJ+Q7cteWcHtWMMFHiCZK+g9Huc8aXma3Ly9JbrraH8IiKsId8ZtPI1YdsfauPKsQCE55pVEkwyw1qG8BjQgXZn9RW4tyWag1kOIAlz7NW0AKsF33umLWstvaMhCuKzrEAKHcGO2p0pWOc1+swsnENfMGNpAbljCAjJpUduEXH4X5XuBdaqiqhkngEYLbSkQ2OCNXXcOHnhUgHECeHXPlF3LHctByRArhiL9SKCFnYzRwJidazm4bpwJC18KEIjNBZeGUtno6NErlKVOOa/oB/5NnXw=='
        token-endpoint: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/token
