eureka:
  client:
    enabled: true
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:8761/eureka/

logging:
  level:
    ROOT: info
    org.bremersee: debug
    org.springframework: info

server:
  port: ${SERVER_PORT:8020}
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port

turbine:
  aggregator:
    cluster-config: BREMERSEE-API-AGGREGATE
  app-config: BREMERSEE-API-AGGREGATE

---

spring:
  profiles: logfiles

logging:
  path: /var/log/hystrix
  file:
    max-history: 25

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/hystrix

