bremersee:
  actuator:
    auth:
      jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.jwk-set-uri:}
  linkman:
    excluded-roles:
      - "offline_access"
      - "uma_authorization"
    excluded-groups:
      - "Allowed RODC Password Replication Group"
      - "Cert Publishers"
      - "Denied RODC Password Replication Group"
      - "DnsAdmins"
      - "DnsUpdateProxy"
      - "Domain Admins"
      - "Domain Computers"
      - "Domain Controllers"
      - "Domain Guests"
      - "Domain Users"
      - "Enterprise Admins"
      - "Enterprise Read-only Domain Controllers"
      - "Group Policy Creator Owners"
      - "RAS and IAS Servers"
      - "Read-only Domain Controllers"
      - "Schema Admins"
      - "xxx"

management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95

---

spring:
  profiles: swarm
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://localhost:9411/
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:unknown}
    instance-id: ${spring.application.name}_${eureka.instance.hostname}
    non-secure-port: ${server.port:80}
    metadata-map:
      user.name: '{cipher}AQBtTH9N2P5gRb1w27Snd4O0eben9jBkpWvLcaq8XO2MIO4O22tsNiQUIKBwYV6FulzQvy5hV5yRthjkgznJ0U6YzZB86WhijHxDG39fJ33OBTrnDid5MBMnDtE1TDbNz5QQwKrLgGsY+sNfXwyrAtpivPsk3yq0NxJDaqm5Dcix5M0oxAr4qyBQ4bVf6D/NuXb4hmWJtsa+yFI6gwsZimvVKVJaks4n6ruGEaJzgZuaCcAog2YtgF6B3v2xIaoKfyoRD2BwrfE+w4Hwy7Z0DjHxNFpQv6P1zJEUuqks/tuadhYSjxsUFB4ZHD8vfB1hyRQZbAcwvmJEwY2RoxuI4cUcD16byfFutq70WFISnl3ZeC9ebQBEFhuMiCO7fp9NryE='
      user.password: '{cipher}AQA+8KzLCa8EvZiGfF1089gugs09TduEFNy4d8QhCOtmKcly+sBM9HWPusazZjkDHE52m6tznRip4Wkcv9LbRvsevnZK0Cq3SkxB55ZTM+Mn0WzZMO9NEYv1H2DcX+sD+Ykr7RBuZTU1uYKvOMe+TpR24LBkg/Aa+1/xFdcrRwtNY5jRTCoUpzxI2ECT0zS/NL/21zuDBgj9QrPyHWUXVHd29icI4klF+pRfyCZrzx5J9lrd5lMQqU6eUfwPlfCGiKMdxftcINOXtkKywcBt+9LuEWQQTRKze1Vws9N2Hm2A0aQa/+0bgsmZcJ03i9saiHdyztj4PHnC9XxdkThfSlIslI/Qw7bLSRRHDAiv18rgxfytz8eiuytV8zOQW6IBByY='
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka1:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka2:8761/eureka/,http://${bremersee.auth.eureka.username}:${bremersee.auth.eureka.password}@eureka3:8761/eureka/

logging:
  file:
    name: /opt/log/${eureka.instance.instance-id}.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  endpoint:
    logfile:
      external-file: ${logging.file.name}

server:
  forward-headers-strategy: framework

bremersee:
  actuator:
    auth:
      enable-cors: false
      password-flow:
        token-endpoint: ${bremersee.auth.client-credentials-flow.token-endpoint}
        client-id: ${bremersee.auth.client-credentials-flow.client-id}
        client-secret: ${bremersee.auth.client-credentials-flow.client-secret}
  cors:
    enable: false
  redis:
    embedded: false

---

spring:
  profiles: dev
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.7
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs
  data:
    mongodb:
      uri: '{cipher}AQAjJGH7zYa5FXj7GGvRePTIv9D9e1+CQyLY6RuCDVIh+/nWymVijWttfiSM1qfcuuKNYJhzgYjfqBaGhCIlGTrpVopXc18k9dmsA17dXTIo+WFp4GOBLpSFpk3+vhYM/2ZL3DIqg9PK+QjKuzg7Ro8bjM01qudaUEzJ/t9Z7Ukx1Z4hsPOOzD9iLAqh7BVtdzcvpEASXiguQ7kIdmVpHkaOdQ+GXGZGKhCbiYPrB+C3lY2W7ubFj63GBiNQlyQmwB+TwvhD+eGb0ZWNJftjMVbF7x92Ydpe4AB0wNBYmRACJ6EKbEPlLbPnfDWfTNXRq7EOURz4UOtTNu+A1Oaqy4q5CgErETWWOtwYYooz7mMOTHp0x5OuwvMs3MF5fgVaBXub3NUvse+cgsaIGeqMnBCO9fWKT9phogBHG+1cLBl1lNvDWoHNmBXfo12pkHZKFgeKXhcRV9Z47ts56y1T4VhGVLQEfP8sxyX+L5ch/8Lbb5qR3h18w9iwOishMCSoLLIPADJobWsrJLMaE/6JmeBK'
  redis:
    password: '{cipher}AQCTSztA3PgRXP1gZTSCqkY5wPkSU6RbBrNYty1d8vd7NaXpbBFXb4eaCgH6R1nkd7Atmgmk5O+ozezlDTciWF7pZaN/IQt/ZkosrgGgoo5OkJ7zuB+zrdk8xr5CGN2fDIuXM6mHDOLt5EM4GnYuIJ42FyEZWCYu5CewgWvDGE59Fdp9/8wLsapbaE96OPgGDkhzGI7u/f7K8aHu+Z1MhTHsLAuFSy4ikBXKYAYdvvEb0izxrp684ME+Hr9l9Fq1/GEcFV7aw2ahoU0H/p35aHoGMYZpbkAqgZTmf3XrkJ8f/eGNgo7BcGwMciVOts3ZS5ezHwRhzngfmN4Utk+pjxHNtIkuNmAQZB1YRCzXGRE8pZ9su/wdL/BuCmE4xeDvoyGQAJJiUOdtNgC0hk6C9vwH'
    cluster:
      nodes: "192.168.1.41:6379,192.168.1.42:6379,192.168.1.43:6379,192.168.1.44:6379,192.168.1.45:6379,192.168.1.46:6379"

bremersee:
  auth:
    eureka:
      username: '{cipher}AQBWGFbNNMTwWBU5Pqf9M2C5I3sazPDF6qPpVTCGhKtsvEHPBleMD3mYUfDwCFzZEgDoHEjjW1eVILrib+S1JrNbOwdkkg8QY7S1DgOEeiy6qNHUspI8j5bMCvoYkx/m0umGh6NfOUNCxk34PDjF6hH9K5kppRhAANUeLF/vtji/NF9WRl0jrmf79aHUyxVvu87Vpd70KdlP3s2UhADa5b6ePwLWwcfczQX5ibxnobXEaeOoPNFaKOXoC9SG7BACsgT3KPW0DIfu/GXi/skbAg0QZnvRn1uBYIXfkf8ix//lZFZ57M2WQDcHgdHlNf+/oOoo7IoTT4kjKuIwzUd9EK+aJYRtSez8VFk/rk+vG4E+UShfveH9WbJHY4UzIlWuNu8='
      password: '{cipher}AQBSTXFR5pCi01YxMJ7APS/OHt+dopgHHaKjl7irWamHxXYbJixsccArznT+LNWKzJoAYcx98KLoLVyMLbTs0HkS9ru2PnkvsWmhgnwcfcQwysTyxLNba/2NOIT6riujcvggJNxFhkT0iRhuF4Hk74gK64DBqYxbi99voGMQC6OI4FDYBb8ci6UxZsIVTkUYLHPv2nW9ympf/wUlgp2GBJh0IsCYQztXF1pTTlKXGly+Q6VlhwNlFZvQSE6jri17ANUoAG78247DIoDc1U/8OsHViVCcTVJA/Nl+D7fey7s99qAQBtzFW0Lz7rHf5wNn2nIUeCul9+ai9afWlF7m8iBGW/JhtNXf/9cRDc91jKhGfwqin48OYYnb+8oRkD/plWzw84e32c8SK6qr7D/aGri9'
    client-credentials-flow:
      token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
      client-id: '{cipher}AQB1TsOgfpx9tJXZSTmS3hA47jl66arYv/IxBmxX4Q6r1ImRI7tof/YcyZcAL/Dw/r+vXsy6KD45xfgavcFsta6Nl3NU53c5s/mYOe98cTe/68VgLfpm4eRI/Emf34sjQRM4sJkCoHcH8mEZgndrlRoqX2F350+nHcLJ2rKDV4rhqhkE0MJKVOkdkhzsuTvH+5qRzg6dLxo2GWiYKUJr4bTx3LXR7AXIiUCG5IQKCxJvb6aUbqpFTdSffdbvwucKgIiFpzBeNZBxwNJet8HL/uA1E6wLL2dbefiF4exajmCrKadBFBRgFUit78ciq2TTj0C7Kk0mhmCwUvirhw8wNXltBP9VNPZxZOYR0xE7oxtFQsrLU4vJgwMrhS5Wvqpbq5I='
      client-secret: '{cipher}AQAVW00d4td2nvh6npScnTItTFkA3Fs5ZjnZ0e4M1mlhJ3HYNTIhW05y+xSV4qxp4hGC3qc9dOwbSYY74hJMQMcFfFDQ81PEK7+R64CYzS1OcQ2i191IqKX4ynjBZPfsF74STqWYi92N/eOI4004qUiTz1rRPmt1fEpCr2wH+hnihKOnkYjIQrekKWWxEab1YlHReavb5X05cMGyGe1AT23j1SWuKYnQHPC1XxjCo6/5FxAFtOlHnGFT2tV+1I9amcbfV4F2tvOSRFtOrJAZeZ7QvXCKBRFAGovP5PPZ//m65Z5BDYLcGUivGAjiphH+F1Wi7uNPQ4HztwijwFf8UM9RlU1eCiRnKLQs0WJ4KS91P7uCeKKE8BzXV9EPWExVMqacPnUv6AcDwXb2PxjHgOgJ2Sy2HN4MD47wrLL2HXcbwg=='
  linkman:
    groupman-base-uri: http://groupman
    keycloak-base-uri: https://openid.dev.bremersee.org/auth
    keycloak-realm: omnia

---

spring:
  profiles: prod
  cloud:
    inetutils:
      preferred-networks:
        - 172.16.1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/certs
  data:
    mongodb:
      uri: '{cipher}AQCXcH3gQBqpb8Pgi7Q7U4+BLx8lEjSP0ss9C7RmFic6TlssZuP7IKyf36psX6az65l6q62VKu2w3Ftm+C5tBaSh1kMGB16I75DDYB+JsQ3pNJ/uQqcZ553UYXiLgW02LZcjlWlLOpNzQKkqGqak+6Js8M9cOFevcd9fGnXcDolE8s1d9RWIk5ZcV4xy5jvzn+BFVrkizop7waCw2WPA07BLU9P18z7P/AnppF8JcU15ZZnv3sT2BWLQTAb/QccJfp4igSjwBCOyiZyct59erJrIrEpMoZyu/GXm3Si4Vinx9DXCFmiJXyh9ScQADh2i8xiJ1V7BFUCa4lYMpfbocVjpryJn0D+AQiwUUNHdES13hHn7sgyHb0I0eGUNWkykYOzmQaD5M3myLfp/j0JjAoBsiDlQeG/ms6+zvW6XSlv960KRk0+OlBVSImAiVX6dxHasE+UzVc7IuNd3U6br5lu88tBODltomBONIQiizanKJjfeE5BUl/wFwhQ8SeL1t5LERm4/PpKtb9U/lZmN6GSP'
  redis:
    password: '{cipher}AQAN3SBtcObu2mRWgqu3m+94OEroGqz6d7vZCIZcIKDI0WJAHmuQNXmtHW4zkemnBdpzR0OX2W749Abpk/8E8G5GuKK2E1tCIqDSG3ItAlhjJ6kFGjET0/oOaB2LFIXZNwqAz34Z2tc2OIu+7NtzGywQuLzrr7J8nH0PLjdvdGdAWyH06lxAuW/MsnJfiORW8CBmvsyjFEo2smlHY2jnMZPTEprVGYIJq670O+W1WokxVjjUEIow4zpczRTBiFn/J85UoQduju8aMTxQJEQAVsFpTNj6PBMEbSjVDxZfRqej80UgR9SXBU6z73GWzT6si9K6s2Az4parCKsp1UpB0ubvXFNI8ZddgfXEN7ccUM5JQpFuHA8KTfqylulL9LHxGbliQjrLi5lishbYfcrVQcBc'
    cluster:
      nodes: "192.168.1.51:6379,192.168.1.52:6379,192.168.1.53:6379,192.168.1.54:6379,192.168.1.55:6379,192.168.1.56:6379"

bremersee:
  auth:
    eureka:
      username: '{cipher}AQAs/zyqDN6WusLJP5Lu4P8JK13EPMbvVJt01OSbbycBsGW9SQ/GChI51LMLLV6+TOjnGDLVqFBxHT06s37ugAIzPS9UlDtsNRsUx2hWyDsYW1AIH9dV1ikijuNgg3edTLJOJ2RhJkXmdb9+q3sdAMgBmOxQafbOftAvRKlhfBLkviYJG9Nv8Pi3P6RDP6eyCs8119wIv3LWe2BVJbLbo9Xn8FTAM8yC8a3D1SIG48J7stDWDln4WPDax8Tc/w4Qvrn3/y2fIIr+uSye4gXOaLs5YbqQTVtqGwpBj9eB/H6pSCOuxhj+plKP9cl13VIA31lEvJWzKAFOK8H//rI10cwcXoI7Ev7AEMKke58kifAvUyhPjLQl7Px6hhf3FB/TqM0='
      password: '{cipher}AQAgP5Z8+CWJX/sy5g9yF4qmCMSxfn6BfvXellyt+SXDLins5BSiRac7ppOD8bdE7g7QGD+GFyYjYYbWVEJdjtRmgGh3GIvOJNrIHzS8LF7SsyebpTP64Lc0hOgkH3RVOEtngItXTortn85FyVieYkQaP20ssHrYMSHvhaYYxSuBuFE2XTwXZMlg8Wvz3yW2hHDVMlRgz+kRZgc5P0COJbtjOXn0yR8MBB6CyzLjgG4Ul657rQZEPNgv+fduDxGvseK0yAM1XFBpfDLBlD5nCGO3w42b1UtR0LplK5SQH8WbD6NMYT4LA8SAUQDx4Q0ATNOnn14Au1GKzfZtflCKGbbakhG+BG/IrzvzNa/gjQxEkfx5+bvDx5jdIVqiD4c3T+V1v/OQgtIF+/7PeZK/3dL+'
    client-credentials-flow:
      token-endpoint: https://openid.bremersee.org/auth/realms/omnis/protocol/openid-connect/token
      client-id: '{cipher}AQB1TsOgfpx9tJXZSTmS3hA47jl66arYv/IxBmxX4Q6r1ImRI7tof/YcyZcAL/Dw/r+vXsy6KD45xfgavcFsta6Nl3NU53c5s/mYOe98cTe/68VgLfpm4eRI/Emf34sjQRM4sJkCoHcH8mEZgndrlRoqX2F350+nHcLJ2rKDV4rhqhkE0MJKVOkdkhzsuTvH+5qRzg6dLxo2GWiYKUJr4bTx3LXR7AXIiUCG5IQKCxJvb6aUbqpFTdSffdbvwucKgIiFpzBeNZBxwNJet8HL/uA1E6wLL2dbefiF4exajmCrKadBFBRgFUit78ciq2TTj0C7Kk0mhmCwUvirhw8wNXltBP9VNPZxZOYR0xE7oxtFQsrLU4vJgwMrhS5Wvqpbq5I='
      client-secret: '{cipher}AQAG4FTBBhQ1jKOKrBT4rcEWEIsgj46XDdss8VuqsPc4Xf640lJMc97NKox/U5srs+LGwq2i3Z0FsqR4RQsamZhiUfGsBvDOTnt63sqH8EPhNbQyJlY2whLj1PeRvvNS3X0p87CkBXwKeyo7idj0GoTGOHSARSU+hd3e4yhj/DzFUlQgw+1vQ0rBJNor04P8apcNW6DlMgG07fsxvOaj4pYe2f4xuLJrMuV3tvZ1ggIReRk4NAjHGJF4kahy3m3k67hA0vmEdkYEr5EOnJdnjcQKHYJk220u2zoWHWU0XJnAQRsyXWUn312yzHXmYYpdgDX8FYvqMxRcz62Uuv6LLAVIVG2JYCgL2Z0nWWAiYzMPKGEE2wBgnUGRp4m+DQHvmFtwSTYMUZa30/9NeanrYYWjxit+oVp0j9wnBdHQ+3hq0Q=='
  linkman:
    groupman-base-uri: http://groupman
    keycloak-base-uri: https://openid.bremersee.org/auth
    keycloak-realm: omnis

---

spring:
  profiles: local
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs
  data:
    mongodb:
      uri: '{cipher}AQBU5XAoGBzC5aajDANwjhZaivLUJ0euEFBOaxyKYxkAdPBsXWEXBkcMbmdfOI4XoUCISZ+/QXKLdfRBITX0GRmaCyZtfFNqv2bZe7YjSNO6zcTQdaxZJo0kMCyUVUqUIwpa+c9O11ucc2jjLFSwy9yG3Dony2P9i9w8sxiPHqH1/zK51L9pyLK2NMAfCp0K46crtVxoBvsD817gljLjhXt6Bqg4QSMcUY9ofEAb6PXoXw3XL46yegCmJZ78ueU+0Tucib5wlFdxoh1xA8H8ohCSPlRa7m7RZVAxonJtlSXe2eZWIzHhqrxQpaIoJOvVMQpDgUgSJthc7PMQcPtLsCjNGX1a8otEf4KYuXxqrZYASlXxY5uzKPY8g/pBmKdOzgzsajbn0U1VgswlVaWgNWhXo/ZWUtKqKdCeMHUTTJRm9tpeFJ33TGBcLpwxtiwH6+YHAHQYxqgkFrR5yyCsplHfsqL9BYYPqtJCJSpYlFbehg=='

bremersee:
  auth:
    client-credentials-flow:
      token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
      client-id: '{cipher}AQB1TsOgfpx9tJXZSTmS3hA47jl66arYv/IxBmxX4Q6r1ImRI7tof/YcyZcAL/Dw/r+vXsy6KD45xfgavcFsta6Nl3NU53c5s/mYOe98cTe/68VgLfpm4eRI/Emf34sjQRM4sJkCoHcH8mEZgndrlRoqX2F350+nHcLJ2rKDV4rhqhkE0MJKVOkdkhzsuTvH+5qRzg6dLxo2GWiYKUJr4bTx3LXR7AXIiUCG5IQKCxJvb6aUbqpFTdSffdbvwucKgIiFpzBeNZBxwNJet8HL/uA1E6wLL2dbefiF4exajmCrKadBFBRgFUit78ciq2TTj0C7Kk0mhmCwUvirhw8wNXltBP9VNPZxZOYR0xE7oxtFQsrLU4vJgwMrhS5Wvqpbq5I='
      client-secret: '{cipher}AQAVW00d4td2nvh6npScnTItTFkA3Fs5ZjnZ0e4M1mlhJ3HYNTIhW05y+xSV4qxp4hGC3qc9dOwbSYY74hJMQMcFfFDQ81PEK7+R64CYzS1OcQ2i191IqKX4ynjBZPfsF74STqWYi92N/eOI4004qUiTz1rRPmt1fEpCr2wH+hnihKOnkYjIQrekKWWxEab1YlHReavb5X05cMGyGe1AT23j1SWuKYnQHPC1XxjCo6/5FxAFtOlHnGFT2tV+1I9amcbfV4F2tvOSRFtOrJAZeZ7QvXCKBRFAGovP5PPZ//m65Z5BDYLcGUivGAjiphH+F1Wi7uNPQ4HztwijwFf8UM9RlU1eCiRnKLQs0WJ4KS91P7uCeKKE8BzXV9EPWExVMqacPnUv6AcDwXb2PxjHgOgJ2Sy2HN4MD47wrLL2HXcbwg=='
  actuator:
    auth:
      password-flow:
        token-endpoint: ${bremersee.auth.client-credentials-flow.token-endpoint}
        client-id: ${bremersee.auth.client-credentials-flow.client-id}
        client-secret: ${bremersee.auth.client-credentials-flow.client-secret}
  linkman:
    groupman-base-uri: https://api.dev.bremersee.org/groupman
    keycloak-base-uri: https://openid.dev.bremersee.org/auth
    keycloak-realm: omnia
