management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95

---

spring:
  profiles: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs

  data:
    mongodb:
      uri: '{cipher}AQAjJGH7zYa5FXj7GGvRePTIv9D9e1+CQyLY6RuCDVIh+/nWymVijWttfiSM1qfcuuKNYJhzgYjfqBaGhCIlGTrpVopXc18k9dmsA17dXTIo+WFp4GOBLpSFpk3+vhYM/2ZL3DIqg9PK+QjKuzg7Ro8bjM01qudaUEzJ/t9Z7Ukx1Z4hsPOOzD9iLAqh7BVtdzcvpEASXiguQ7kIdmVpHkaOdQ+GXGZGKhCbiYPrB+C3lY2W7ubFj63GBiNQlyQmwB+TwvhD+eGb0ZWNJftjMVbF7x92Ydpe4AB0wNBYmRACJ6EKbEPlLbPnfDWfTNXRq7EOURz4UOtTNu+A1Oaqy4q5CgErETWWOtwYYooz7mMOTHp0x5OuwvMs3MF5fgVaBXub3NUvse+cgsaIGeqMnBCO9fWKT9phogBHG+1cLBl1lNvDWoHNmBXfo12pkHZKFgeKXhcRV9Z47ts56y1T4VhGVLQEfP8sxyX+L5ch/8Lbb5qR3h18w9iwOishMCSoLLIPADJobWsrJLMaE/6JmeBK'

bremersee:
  security:
    authentication:
      enable-jwt-support: true
      password-flow:
        client-id: linkman
        client-secret: '{cipher}AQAVW00d4td2nvh6npScnTItTFkA3Fs5ZjnZ0e4M1mlhJ3HYNTIhW05y+xSV4qxp4hGC3qc9dOwbSYY74hJMQMcFfFDQ81PEK7+R64CYzS1OcQ2i191IqKX4ynjBZPfsF74STqWYi92N/eOI4004qUiTz1rRPmt1fEpCr2wH+hnihKOnkYjIQrekKWWxEab1YlHReavb5X05cMGyGe1AT23j1SWuKYnQHPC1XxjCo6/5FxAFtOlHnGFT2tV+1I9amcbfV4F2tvOSRFtOrJAZeZ7QvXCKBRFAGovP5PPZ//m65Z5BDYLcGUivGAjiphH+F1Wi7uNPQ4HztwijwFf8UM9RlU1eCiRnKLQs0WJ4KS91P7uCeKKE8BzXV9EPWExVMqacPnUv6AcDwXb2PxjHgOgJ2Sy2HN4MD47wrLL2HXcbwg=='
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
  linkman:
    groupman-base-uri: https://api.dev.bremersee.org/groupman

---

spring:
  profiles: local
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs
  data:
    mongodb:
      uri: '{cipher}AQBU5XAoGBzC5aajDANwjhZaivLUJ0euEFBOaxyKYxkAdPBsXWEXBkcMbmdfOI4XoUCISZ+/QXKLdfRBITX0GRmaCyZtfFNqv2bZe7YjSNO6zcTQdaxZJo0kMCyUVUqUIwpa+c9O11ucc2jjLFSwy9yG3Dony2P9i9w8sxiPHqH1/zK51L9pyLK2NMAfCp0K46crtVxoBvsD817gljLjhXt6Bqg4QSMcUY9ofEAb6PXoXw3XL46yegCmJZ78ueU+0Tucib5wlFdxoh1xA8H8ohCSPlRa7m7RZVAxonJtlSXe2eZWIzHhqrxQpaIoJOvVMQpDgUgSJthc7PMQcPtLsCjNGX1a8otEf4KYuXxqrZYASlXxY5uzKPY8g/pBmKdOzgzsajbn0U1VgswlVaWgNWhXo/ZWUtKqKdCeMHUTTJRm9tpeFJ33TGBcLpwxtiwH6+YHAHQYxqgkFrR5yyCsplHfsqL9BYYPqtJCJSpYlFbehg=='

bremersee:
  security:
    authentication:
      enable-jwt-support: true
      password-flow:
        client-id: linkman
        client-secret: '{cipher}AQAVW00d4td2nvh6npScnTItTFkA3Fs5ZjnZ0e4M1mlhJ3HYNTIhW05y+xSV4qxp4hGC3qc9dOwbSYY74hJMQMcFfFDQ81PEK7+R64CYzS1OcQ2i191IqKX4ynjBZPfsF74STqWYi92N/eOI4004qUiTz1rRPmt1fEpCr2wH+hnihKOnkYjIQrekKWWxEab1YlHReavb5X05cMGyGe1AT23j1SWuKYnQHPC1XxjCo6/5FxAFtOlHnGFT2tV+1I9amcbfV4F2tvOSRFtOrJAZeZ7QvXCKBRFAGovP5PPZ//m65Z5BDYLcGUivGAjiphH+F1Wi7uNPQ4HztwijwFf8UM9RlU1eCiRnKLQs0WJ4KS91P7uCeKKE8BzXV9EPWExVMqacPnUv6AcDwXb2PxjHgOgJ2Sy2HN4MD47wrLL2HXcbwg=='
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
  linkman:
    groupman-base-uri: https://api.dev.bremersee.org/groupman
