spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT
  sleuth:
    enabled: ${SLEUTH_ENABLED:false}
    sampler:
      probability: ${SLEUTH_PROBABILITY:1.0}
  zipkin:
    enabled: ${ZIPKIN_ENABLED:false}
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411/}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OPENID_KEYS_URI:https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    ROOT: info
    org.bremersee: debug
    reactor: info
    org.springframework: info

bremersee:
  security:
    cors:
      allow-all: false
      configs:
        - path-pattern: "/**"
          allowed-origins:
            - "*"
          allowed-methods:
            - "*"
          allowed-headers:
            - "*"
    oauth2:
      password-flow:
        client-id: ${OPENID_CLIENT_ID:omnia}
        client-secret: ${OPENID_CLIENT_SECRET:changeit}
        token-endpoint: ${OPENID_TOKEN_ENDPOINT:https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token}
  exception-mapping:
    api-paths:
      - /api/**
    exception-mappings:
      - exception-class-name: org.springframework.dao.DuplicateKeyException
        status: 409
        message: "Entry already exists."
        code: "PER:1000"
      - exception-class-name: org.springframework.dao.OptimisticLockingFailureException
        status: 409
        message: "Version is not up to date."
        code: "PER:1001"
  tomtom:
    key: '{cipher}AQCf7fnCGm4+fSS+xejcWjlwhwpCUPHRRpSaNc3G22nXH1UIsC5IkAVCQ2COcExPycThS3v1WNS+Abtip2WdfNBjXVo0mWgEWVox3H8Ht3ZxVvdywzS68yrLJSbF6gLtSR0xSoi0xiYs8KHcWJKycaIGMFk+a9/3ig0uf6IfNLGNb+LsO4sV9ndJjCNby0CjSFB8b4RHYf9FqZ7E6yXW46jpUjMXeMNJQcd/fJskpO1xV7+/RKvME4GOfjA2oFxW2jdni5oW5tuayeaqJUL6S3mC/Ux4EPJPr4kwFqCGFuvEZS9SUKK3nbyos2BjiJBLYHkqNmbU/apcXKqNbcZb7bx9vCFEV0oqc/e9WJ6AtN1SqSIhaoaq20zBeakQP9p8krqqW14ESI15QQiEPZPLj/xjfbqu0SMaieSGDXt6eqXm1Q=='

---

spring:
  profiles: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs

  data:
    mongodb:
      uri: '{cipher}AQBgm4gfpGHCHVwi/pLPyDlJJHNoTRT6qO+zZaAyNfzjvqOhit7ZUhxPnzdc+Mtc4JqWXWrX/4cPgFwb54sJfo2w8FL6olLL9yP4/2SI7pcWNf0KFuoRLQsPYbVofg5G/juLKwRMiM3LSce5YEkictMDtnCH4FE97hF3cBuWadg8XnAdLD1Mav3F+UyS6QCt1AMZ7LjcR+CKkTJ9ZEBUjabTlodtKIS/6vclUiek6/u+X7eVkTJxmyRDC/TFK1WdjToZb0FXSk4KhvQNo95l6iRN7yPR3ZYU/BY8M7D5n96/0MR3UWN/sR5Lzx/6oo9L6H7Uo7CGobmNxj+nAVETMeUEIqkeu+DG+olo4fdTZETgiJ4WBydBtPbA1hIdNHK/RblhbaLE9hm+IoBEphMGoWxAkgIphaQ6ivRFt27poX5wrJPXx/NVi1+RSk2pL+tYWk5SzzW1ACLjIo6pGDpK4pF4LxN1Vhqarm5OHpDUUuv9owgjWd02tV2aRj+i255kQ2QCtOgpsz3h3A02h1hjUqg6'

bremersee:
  security:
    oauth2:
      password-flow:
        client-id: omnia
        client-secret: '{cipher}AQB8JweoVtCLnpj5fbjSJk+5chSTYfewd9iyw4OGktef73BplB4Qp0br4j33y4koFpWgEknSWJaQC4PB1z6TQQUHKfiut8XnmvJf6LcrT7Jk4fg5dGu6xbwe2QBcs352rv5PgnYg7aWRcxMfIie1ukI+nE46F0nRXv0JxBNMMI1KCRHSjtkNxNAsiWKa4VR3gNzPCg3HXbh0xzvJcKu/tkiQbzgZhcF3uuaX0Wl99c2oCwwqfg9nvZy+0v7hlb86bES9DbkCtVG1WiDIG86MSn4gSXk0NrxWux0XlZRdgxNCgZ1IHr+X3UWtpbyiZ58T69AkWD5FmvI89cEWwqnhnqHlibjwbLPM5WXhnKSm8gcZnivAx1r4M0tX0TL3v46+8C0azrJXaL5TwTcn3IBLRk7X5IigQgixQ+5b5VgN5fkuzg=='
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
  peregrinus:
    groupman-base-uri: https://api.dev.bremersee.org/groupman
