eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:unknown}
    instance-id: ${spring.application.name}_${eureka.instance.hostname}
    non-secure-port: ${server.port:80}

  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/"

logging:
  file:
    name: /opt/log/${eureka.instance.instance-id}.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

---

spring:
  profiles: dev
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.7

---

spring:
  profiles: prod
  cloud:
    inetutils:
      preferred-networks:
        - 172.16.1
