info:
  app:
    name: ${spring.application.name}
    version: 1.0.0-SNAPSHOT
    description: Bremersee's samba connector.

bremersee:
  access:
    ip-addresses:
      - "127.0.0.1"
      - "::1"
    users:
      - name: '{cipher}AQB3zheUMt4P4iFEH/IXoelu8V3bTcZsbGxCpjISasmE4z/Dd7Rb7Jn2DMC75VEIqDQ++GGdKDmY49K2XdyEH5hzBDV91jy0FEH9TXyUMtlVnysnXzLuGywBL8L6DyRo02o/xcHg7/ufieci6b1tGreEyC94FG/XkQfK2HTILTEQ+WWGB7xIBgWvBz1AiHofEjhMv/9eZlRNSetVZClLwhwALnvu85SDTGL84WyCKzH/fcItHHk9Gi2mwA2f0yGO8MZvcB2ia/ff9l5Ag2W240sNYC2bJ1iGzhYB81Pn/+XTUgws//dzBxpRou+/bXGEH3nKaDwLxZMFczzEZ27XqvzgA3yRbbFAMhvjU/Jbnp2jmQx/C3WxzqEDT29hrPjUG6c='
        password: '{cipher}AQCKY3d/Bg49RaRTGRM2mj5c5fwIYMZJlyo2rrl8a+Qpzbqg3rO4112PbdN1crKdjx1sfEBdDs4AmUqomwQ7c+cH433f8qCWADtZz6gST8IJe2o2LfYn0pOIktfBSlWTwr2P9M6fh6di/W0YYaJOVttp+6qK5uAK0WJ6mMGQQwpZG9unX53HHYCOzaoVTalNmOQ7lHg6AXx/BwX/WH9UnBiFJ8OOx0n4FgAX79AUuLOYO56oKiWP2chUT1L893iyAeevSXGtJfI1uVByFVbtTh0lzCNoWGrAtyb8+uov0C81xl/wA0Md4ATlQmJ+QhSHDgsgFnAh+9ThuuKWZ/C3LP3x/3LGWoisqUNLeLYJFIvqSQ98fuUM7wrTmNXxxKIRjYY='
      - name: '{cipher}AQCjoXtM2vJHWCpbxbtmQlG/GlHsuoT++/FA7UmDsr6obiTpfOpyoEES5hfDOeRkZIpZkn345TkrJOCul0o++Dkxep3LvGJEEz1Xc5YUbk6ZCROyBERvGbO2yD8oC+0iGWVbDW4rthLDUNoedgJwTuXIRRcXncL9NCjjMBQdcS0gZSoKasAssTj19AsITgvuE2LIeVpDveqZ7NhQTrIgf49tIvRtCocJoj3s13tCCXL5c+z4FZDzDO/Mc9xCdd7iIBrraeOIpzAgRvPJgWDQT95IoK6UBZw1w5HuXgEDTxu9EWGdUhaekO5SO10vGuMgL6ZTTlFkYM8aD0gexfeAi3pgaY8+Sc4XvE6r/DSvsRdqevmb0CN1Vlc3p5fOZdJVTiI='
        password: '{cipher}AQCBDBBqfBE1H3GNQTdrMWrB+ou7Q00ZhYv+Yxh64xETOrPQa+pzg6hxoswZbeJ7wxRNjZC3ARN8p3Isn9XWqzbnReeDDbAIjWg5Y7bMfuhstTWNbf3Chq990wvoTFLhW2lKZAcLMdHKOeVcSYGJ9z5HRZJJ2fuGG3Qnx5BRgf0oH2hYU9qOogTBfI2w8KaJFvdvOMnVscyvItYSva7eVIU62PiqeDO8nG83hBt2cSGvsVNRMF8x8deR7dd8PAC+kS5CEpPJAIstvoLY9PixuRS23SlpTPDjjURg1tGWQRWigUVw45RAlY7GBa0CdJQnmaPmngx3cJABomATzjV7z8EWwpdb+9qPX8g13ufnhBCuhbwPv73N1l05+B6X89ggs9I='
  ldaptive:
    ldap-url: '{cipher}AQAX2yD36v8op/yw5wfo3JjSsG8JcFDeUY1U5QXZ2FPVwT89jtYNJJu7JiG4Fy2Pgh3qq37mdLXpSYDkv+t6VhdX93VMW4YpTmebtUUHTsakBr/9QaAWRl7bpZN2IiZzrqAZGCs/DYsBZbuTxZ8B3xgZwtxJbpcZc9xq+EJN6tlZiVUV6jJvC6JXE3sroYIKVoNtQAOXleJwSoDRBLejFJjpec3Lct8TiWTACUPYi7D+7YQhh50AMgBqBr1J+MdX42qADySsCrooRz/B/wtKcCVFm5yS/NNhsKepiTheDXy2BNXryzzz939wGUay7Z076EsiaFGhE07LS4QxskMiewysmPHQPghrHavYL7RfAlE/Qln3KEf4ur7B3+hzZ1OKGdydVmtty24DdGGdMGtY77peyqwVXBJqMq3dVUu7L8uLgg=='
    use-ssl: true
    bind-dn: '{cipher}AQBAyUg8HKpK2KNQxr89z/3tnpEuVuT4+2kbdgNq/ezxdi0254pRXn0GNOjTkIOT01tMrKPUcUBgZj/1WFkSuBD7H3Q0WR/tYMT644pZzwC4Jpn/j8SWRcHqJKDAq72W3tbVdOzG7v0mu+29hY6qcVx8/9+cZPYyScLz4CGUvSIx+xq1Hlv4hIbixvVCOPzJWoTpTuqGrYwXu0O3G1Wru+GhK0tfRlwnCbKyiac4yIa+HBAahMV548+oQqiD7AXXp6BDYIODo7kBBsQk3aFWIu9PdFZKeQrXgQ7zZ8SS0HPJ+mESt96nT+xDkur5PgwnmQUc6mEoNDGCoQBRpMEseAaS1HjiJCPs/ry9IyRtj1n9vLmkuTXHNc6351NtKZy4s4T6n+hA4zJdO1Gas4CPPJvPRjzNeLye78UiKXlR43X96g=='
    bind-credential: '{cipher}AQBFsE6aRbmoiZfWYqR80BKl6mLOgB58tJ82RaKUScgqnNBXW+qBoXzkNwiQfWbahH3lGWRsV6QgZJOyXBWP0tB5ePRAhJCZcRi67zVyBXzqlvAXGn0RF97Qf260yBKoBVFrdEcGUODruuG0vb9SiGfLuxhSxhE0iGl4ubhWucDnS8bKiH3wW6qB0t7HYfHsHg/YkIgZDD0vgOpvAG+7ckIR9NXsH6LPCf4ai80KVC3ShPD8/gMGhv6DrSLAHoItxyO0u//Kb7iRPaVLvFh4RWd2KVhAbzeQAR3xYKLUkJGkpGd1WarKGDbkB2THaM6s2PL3toIwMMka6L7gYYj4GIIsJNZ3EDswKcDdpYcjZ53nGb1ZLF7ZKcYFKzOiHNPW+nZFpMZN7Iz/GR7OXj/Q/hP1'
    pooled: true
    min-pool-size: 3
    max-pool-size: 10
    validate-on-check-in: false
    validate-on-check-out: false
    validate-periodically: true
    validate-period: 300
    idle-time: 600
    block-wait-time: 10000
    search-validator:
      search-request:
        base-dn: '{cipher}AQA53HABfWRhUyGzZwk69utGvRG9gC5FbuTKfNw6nUqizsWSLghVsxdMHTrh2SwqaTYu1igPIkvsxo2Md6UPLmKARfvkc3uWD1YU2Xp+o4/+EpLas2d61tTfbCmgW5dMVqLd9fwmj036XL54AHNo34UkEJVuyalxtc1Ka6PdZIYzePCd6vpZYKHyeikbVTN0NB9pxJbqyxKl3ewM5pLBvjYGI5kMtpxs7x5R2cehl/mBSMvsy0zO6P5A762G43NBUy1xSfc7j8vLlaWyZ1xGI7LmYpS/btz/GfdBWitBqnDKdIBwQnuxYupBku77RLLwlLax81AFn1vxyjbmFlpq+1iDKc22DjOOcGRGJp6a0oneYPcQqOOI1kQG7EMFMsB8DO7FEpipriuOvI+c6BkUBxdg'
        search-filter:
          filter: (cn=Administrator)
        size-limit: 1
        search-scope: ONELEVEL
        return-attributes:
          - cn
  samba-domain:
    group-base-dn: '{cipher}AQBzcR5wqtrTPMinMCauElYfv0gIrssuefcqEyEDRvRLjlO7xBFwiPaoTQqSSLjaHi9hfFp/e2a/JDQIondWwXjDoXclP07lku8MW/HUyI8ekM/ZThuCLKbXo9X8uQu6qlRxn+LegifqyW4acypKlyN1ayRJYbZ9D71225FJ8W1myRaslAIripY7X1jmosHvHN8s+brK4vdWvqv1Im/OBSITq2kpELre3ncdYGs3lSZ0HR6s/Ygxr8pFd9uNpV2xlFTur5pNeF1CTc7g5vqpMRLrBdSxNR2WIN7ilI+pMiHcGNvsieYJ7Zrvu0mdMpmha/n1Lvz7lChaTyyL7QZMHg98Qbl/IEJdBj/IZsL0XBMkc3yn90dCS4BlKwkudBMzNY3RiqvOmr+niiyaO92TqAmoucxcooe0rniHyN2gTrEHbA=='
    user-base-dn: '{cipher}AQCwRh/8z7UomaFJ6cTregkGjtLrWgskasEol7M4ahCeDJuqa098m9B+iv3cI4TurFbHr8B04o0on1dwBhnRcDjET0qGWr1Njsu7gwyu2arLmFBUyfbaE8+NU5vGLgLYPKoA4ZpvYWdufGMcyXYz3dZOM1qy4W/zBUBWaibbhXMNi/Sa9l/4ysL9ObA90LXpbaSUtp5Z3QPACzV93CMdqHtzlfe7ha56HEPYYQTo5XUFvKbAncCgLfVGPYCc2xcEygYQaVbxRt2+N4fMjGU2O6uSELY86CXrs7OuevMvWc8OAc2GghQUY2kPdRHpJsViWSI/MafUhngAofYr8Ln3LV62IqJ3mCkVnsqDdO5U2ehvWW1iC/BdRbrxuevg/7+WH0niRXV+p8t9H0mCs7fB0o11rbG4R/8MQAOGPAlkjzmr5w=='
    name-server-host: '{cipher}AQCWug0WcPyzL3uj+xKsGYSySqCzS7doO6RMEeUnQPO2hOSr7tRP0MP1seeOx+zl+un3ih9tGCCvcgaJVwF/ti+zrPPpGDXnbkedETnN/F3cW/PYb+dvFkqiCo62CjE3IRKsa9MQ51wZO8CwqQebbXLRLjPbcQWqkHOt6a4tpPLZgjRWHijcLGv/6+2rbhPlAGG1hBe7Lr76erDuYF9qqvk96640Uq5sFh5tPEFkqyrqfPF3mmyaUYXyX4xCupGQhbQ6TKHaVgw6KsN1e6BjhTt2YP2Ov6bQ1QvpP/9tzUdZGjfKhjpvf8hXODGvcupcD1K2HaTvyIIwJ7hVza/ecd406T11hr1CChaoaJQyzs0r44MWRRD8aL94O40IOaJzGdsyDLZ/TjZRmmXErMpmQWfg'

eureka:
  client:
    enabled: true
    register-with-eureka: true
    prefer-same-zone-eureka: true
    service-url:
      defaultZone: '{cipher}AQB2Yv2xI9kHk+uB1HV2Ez79QNFRyot6/XYXydX3QzdW2aodCYUjeFw9BfHvvWdKJpdfkbqFyE3tVJkjS2lOJjp4ojtjXfArTusVmm56BehsvTwX4InO7/2xtLXIPMicdIsXwby3EgrcxnpZQsO+A/ZtfdRbc5fq4j++6TwlbxVYhFJY8L7XNw4lWkdKvu1Px65Q1xdZLMd26Fc0G6qxfZ0N7KG4FSi/EnFo8dBOqIc43gfdvFxMnkcq+fgNPZwNTlbCMoo5qC+UTl6B8lDKUmpLwCBq1jBBBor9pLeBFS2OJ/6hPnIACLU+Z+AXre48EANkH1n/KIWeU8LYiaDnDvRB0JBuJo3sEKCR+ttUKSdST/p+nCRZs0sUJ6m6mSqE30E3N+tfSpjdJE/9rFBUVsMaH2hf7yLr200UPrS8a3IpmRhvUmf6+PI76hsleXk90h5W2xNX/mR0AMH4SUINT7F+'
  instance:
    hostname: '{cipher}AQCx1bQ+0JFTMDzgjJO469rpHSgcGfLCqKvDmhhjkz9/EgUgXuRoaQJJKXX+MlSPFAuPaJ7Vgba6605Cw5VoZusdpGd9KNtJlvb+DkRP9ZSYu9+B4vB4F2xxUVXi4CAiMcBZCuIQhm41vxYYdvCdUzTpzLc8laTRZXCWrDho73pg+yLEKBQEQ1RuGp2ABak5J+ahE4fkcS2ZKQH9VQKfvXLOmlUVgPqdeIbEUfKQWn3/z6Ou39vwbyCybjfXT0ZspAJ7X3EuspSoM8fU3rJGCM/trRnfo1R7jSQMNaRIYN07Y73XPIEjOf/aSQ1ypWK6qSy2LWp3ppb6vl1pXdJt6OMp3rHaPCiSFa/4ZC8b03hmBngNOJQ7V1z09o/QavKpdZgA3SsOXmt+ALGBtwXioU5o'
    ip-address: 192.168.1.5
    non-secure-port: ${server.port}
    non-secure-port-enabled: true
    secure-port-enabled: false
    health-check-url-path: /actuator/health
    health-check-url: https://base-api.bremersee.org/smb-con/actuator/health
    home-page-url-path: /actuator/info
    home-page-url: https://base-api.bremersee.org/smb-con/actuator/info

logging:
  level:
    ROOT: info
    org.bremersee: debug
    org.springframework.cloud.sleuth.zipkin2.sender: debug
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8090
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port

security:
  oauth2:
    client:
      client-id: internal-oauth2-client
      client-secret: '{cipher}AQCCzDbf2pBkLvgzueDdnVIwen20kspj1RQ7p9KwB0520KNt0NO814Ek79QiL+wuoECxrzHUyIUjvgPLj5UFUYRuTR+Y8nwclYBY/EiBqQqjBn+eIlk0hVtwcBlsUE16txHohllDofy+ptGjWPt3SSl1vxsziuNdydLHFn0VcAIfpNzgCXjdL35o/evUfhW0XGCJowzDCkW1VajHA/lw1vzLZ/Dzk07nXgeiG9uyzXZXX6euVdEujOIgazeiPHcnsEd/ngDVA8K9zCYizc/ZSPW9Mei9mn6QrTYUzbE4S3oDie/E/uZkp+kFDD8LjDuIJPs/TP0RMmy6MPMr7XvZGSWw4MdF82fW9tuxxn1yvjzScHfHlpF6D+ug1IcXECY+06ExMw5j+rV9tU6LLvDB3t6b'
    resource:
      jwt:
        #key-uri: https://authman.bremersee.org/oauth/token_key
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApM/zEylsUfxlT7Je8UMJ
          i+tVQjdto6PF8jrfeBivIR1rl1Jbhthx0V2jK92dnjyU6UTUxfP29axMNKRA8/tB
          KlikYZoH4ZmWlx27K2G+49czfQPz0DO5Wn4P4d1ot3zgKNYVfqAjzrDwzAwMLnkm
          X7eZyikhrptyG0war2ZGHJxm3VaENUch1XVVzl8nSeDIzs6Usn40N5IyTrEi5/yw
          wFlGeB04mbulLT5uDZqjk6nBsB2n4vD2qhNSjA2q4BR4DlPLy9T1VlZM286cEk44
          noQjHGhTdPQMG7nNeQL5rnG/7GGs5pJCd53JF3wKEugJxoT1DzTKGhRT0cDlHYyW
          SQIDAQAB
          -----END PUBLIC KEY-----
      token-info-uri: https://authman.bremersee.org/oauth/check_token
      prefer-token-info: false

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Europe/Berlin
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: '{cipher}AQBiv4CvdkrFhwKzFPfSAd3Q6nf6w7FZwxp7/E91ImQET7s/BA2xBR6RuxuO7q/FXZms3pqcOqXkBlkDIx9uxfLGJ/mF2Y8llNx9UVSN4bgww4s3TPr231y83b15LW+aoTI6Ps7ZhX9drMnSnN5zmWJtPHrCnuNeQuLZl6PAPrKAHyVQnSrSValZeZ3NT04fzI3UbJ8h/Z84ELnfEOjSERimEkchNCTdoSWGjywRQMIk4T9ndd7HpbX2j9fnXN/ibvrs0OxZikf5aWA3j+eC9trqNsmOSv5fMowmEsTApeef3kG0w9O1qNOYFDKFcqw7dcHFc6N3rp9J3YENjnYmFeyML/hi60qpVCEU1q4VikBc853OAKob0jLcoYlOgfAz7IGFXasjuvgHs88p5VlmOBjdQVfQO73+5VSxPRhdCKjvVsPtA4Cx1PH5Bue2Gtdd3so='

---

spring:
  profiles: debian9

logging:
  path: /var/log/smb-con
  file:
    max-history: 25

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/smb-con

