eureka:
  client:
    enabled: true
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:8761/eureka/
      # Eureka will be available in the local docker network,
      # if bremersee.access.default-access is set correctly
      # and the docker network is set up accordingly.

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.bremersee: DEBUG

management:
  server:
    servlet:
      context-path: /management

server:
  port: 8765
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Europe/Berlin
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://zipkin:9411

zuul:
  sensitive-headers:
  add-host-header: true
  add-proxy-headers: true
  strip-prefix: true

---

spring:
  profiles: logfiles

logging:
  path: /var/log/zuul
  file:
    max-history: 25

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/zuul

---

spring:
  profiles: base

  zipkin:
    base-url: '{cipher}AQBiv4CvdkrFhwKzFPfSAd3Q6nf6w7FZwxp7/E91ImQET7s/BA2xBR6RuxuO7q/FXZms3pqcOqXkBlkDIx9uxfLGJ/mF2Y8llNx9UVSN4bgww4s3TPr231y83b15LW+aoTI6Ps7ZhX9drMnSnN5zmWJtPHrCnuNeQuLZl6PAPrKAHyVQnSrSValZeZ3NT04fzI3UbJ8h/Z84ELnfEOjSERimEkchNCTdoSWGjywRQMIk4T9ndd7HpbX2j9fnXN/ibvrs0OxZikf5aWA3j+eC9trqNsmOSv5fMowmEsTApeef3kG0w9O1qNOYFDKFcqw7dcHFc6N3rp9J3YENjnYmFeyML/hi60qpVCEU1q4VikBc853OAKob0jLcoYlOgfAz7IGFXasjuvgHs88p5VlmOBjdQVfQO73+5VSxPRhdCKjvVsPtA4Cx1PH5Bue2Gtdd3so='
    service:
      name: base-${spring.application.name}


