#
# For bremersee's zuul version 1.1.0
#
info:
  app:
    name: ${spring.application.name}
    version: 1.1.0
    description: Bremersee's Spring Zuul Server.

bremersee:
  access:
    ip-addresses:
    - "127.0.0.1"
    - "::1"
    - "172.16.238.0/24"
    - "fd2d:6169:6c63:6f77::/64"
    users:
    - name: '{cipher}AQB3zheUMt4P4iFEH/IXoelu8V3bTcZsbGxCpjISasmE4z/Dd7Rb7Jn2DMC75VEIqDQ++GGdKDmY49K2XdyEH5hzBDV91jy0FEH9TXyUMtlVnysnXzLuGywBL8L6DyRo02o/xcHg7/ufieci6b1tGreEyC94FG/XkQfK2HTILTEQ+WWGB7xIBgWvBz1AiHofEjhMv/9eZlRNSetVZClLwhwALnvu85SDTGL84WyCKzH/fcItHHk9Gi2mwA2f0yGO8MZvcB2ia/ff9l5Ag2W240sNYC2bJ1iGzhYB81Pn/+XTUgws//dzBxpRou+/bXGEH3nKaDwLxZMFczzEZ27XqvzgA3yRbbFAMhvjU/Jbnp2jmQx/C3WxzqEDT29hrPjUG6c='
      password: '{cipher}AQCKY3d/Bg49RaRTGRM2mj5c5fwIYMZJlyo2rrl8a+Qpzbqg3rO4112PbdN1crKdjx1sfEBdDs4AmUqomwQ7c+cH433f8qCWADtZz6gST8IJe2o2LfYn0pOIktfBSlWTwr2P9M6fh6di/W0YYaJOVttp+6qK5uAK0WJ6mMGQQwpZG9unX53HHYCOzaoVTalNmOQ7lHg6AXx/BwX/WH9UnBiFJ8OOx0n4FgAX79AUuLOYO56oKiWP2chUT1L893iyAeevSXGtJfI1uVByFVbtTh0lzCNoWGrAtyb8+uov0C81xl/wA0Md4ATlQmJ+QhSHDgsgFnAh+9ThuuKWZ/C3LP3x/3LGWoisqUNLeLYJFIvqSQ98fuUM7wrTmNXxxKIRjYY='
    - name: '{cipher}AQCjoXtM2vJHWCpbxbtmQlG/GlHsuoT++/FA7UmDsr6obiTpfOpyoEES5hfDOeRkZIpZkn345TkrJOCul0o++Dkxep3LvGJEEz1Xc5YUbk6ZCROyBERvGbO2yD8oC+0iGWVbDW4rthLDUNoedgJwTuXIRRcXncL9NCjjMBQdcS0gZSoKasAssTj19AsITgvuE2LIeVpDveqZ7NhQTrIgf49tIvRtCocJoj3s13tCCXL5c+z4FZDzDO/Mc9xCdd7iIBrraeOIpzAgRvPJgWDQT95IoK6UBZw1w5HuXgEDTxu9EWGdUhaekO5SO10vGuMgL6ZTTlFkYM8aD0gexfeAi3pgaY8+Sc4XvE6r/DSvsRdqevmb0CN1Vlc3p5fOZdJVTiI='
      password: '{cipher}AQCBDBBqfBE1H3GNQTdrMWrB+ou7Q00ZhYv+Yxh64xETOrPQa+pzg6hxoswZbeJ7wxRNjZC3ARN8p3Isn9XWqzbnReeDDbAIjWg5Y7bMfuhstTWNbf3Chq990wvoTFLhW2lKZAcLMdHKOeVcSYGJ9z5HRZJJ2fuGG3Qnx5BRgf0oH2hYU9qOogTBfI2w8KaJFvdvOMnVscyvItYSva7eVIU62PiqeDO8nG83hBt2cSGvsVNRMF8x8deR7dd8PAC+kS5CEpPJAIstvoLY9PixuRS23SlpTPDjjURg1tGWQRWigUVw45RAlY7GBa0CdJQnmaPmngx3cJABomATzjV7z8EWwpdb+9qPX8g13ufnhBCuhbwPv73N1l05+B6X89ggs9I='

eureka:
  client:
    enabled: true
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:8761/eureka/
      # Eureka will be available in the local docker network,
      # if bremersee.access.default-access is set correctly
      # and the docker network is set up accordingly.

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.bremersee: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8765
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT
  sleuth:
    sampler:
      probability: 0.1
  zipkin:
    enabled: true
    base-url: http://zipkin:9411

zuul:
  sensitive-headers:
  add-host-header: true
  add-proxy-headers: true
  strip-prefix: true

---

spring:
  profiles: logfiles

logging:
  path: /var/log/zuul
  file:
    max-history: 25

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/zuul

---

spring:
  profiles: base

  zipkin:
    base-url: '{cipher}AQBiv4CvdkrFhwKzFPfSAd3Q6nf6w7FZwxp7/E91ImQET7s/BA2xBR6RuxuO7q/FXZms3pqcOqXkBlkDIx9uxfLGJ/mF2Y8llNx9UVSN4bgww4s3TPr231y83b15LW+aoTI6Ps7ZhX9drMnSnN5zmWJtPHrCnuNeQuLZl6PAPrKAHyVQnSrSValZeZ3NT04fzI3UbJ8h/Z84ELnfEOjSERimEkchNCTdoSWGjywRQMIk4T9ndd7HpbX2j9fnXN/ibvrs0OxZikf5aWA3j+eC9trqNsmOSv5fMowmEsTApeef3kG0w9O1qNOYFDKFcqw7dcHFc6N3rp9J3YENjnYmFeyML/hi60qpVCEU1q4VikBc853OAKob0jLcoYlOgfAz7IGFXasjuvgHs88p5VlmOBjdQVfQO73+5VSxPRhdCKjvVsPtA4Cx1PH5Bue2Gtdd3so='
    service:
      name: base-${spring.application.name}


